grapher_schema: "011"

title:
  title: Chickens killed to produce eggs
  title_variant: ""
topic_tags:
  - Animal Welfare

default_selection:
  - World

default_dimensions:
  metric: total

definitions:
  common_views:
    - config:
        originUrl: ourworldindata.org/animal-welfare
        hasMapTab: true
        tab: map
        chartTypes: ["LineChart", "DiscreteBar"]
        yAxis:
          min: 0

dimensions:
  - slug: metric
    name: Metric
    choices:
      - slug: total
        name: Total
      - slug: per_capita
        name: Per person
      - slug: per_100_eggs
        name: Per 100 eggs

views:
  - dimensions:
      metric: total
    indicators:
      y:
        - catalogPath: chickens_killed_for_eggs#chickens_killed
    config:
      title: Chickens killed to produce eggs

  - dimensions:
      metric: per_capita
    indicators:
      y:
        - catalogPath: chickens_killed_for_eggs#chickens_killed_per_capita
    config:
      title: Chickens killed to produce eggs per person

  - dimensions:
      metric: per_100_eggs
    indicators:
      y:
        - catalogPath: chickens_killed_for_eggs#chickens_killed_per_100_eggs
    config:
      title: Chickens killed to produce eggs per 100 eggs
