version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
  commands:
    - git submodule init
    - git submodule update
    - pip install -U poetry
    - poetry install
    - poetry run mkdocs build
    - mkdir -p _readthedocs
    - cp -r site/ _readthedocs/html/

submodules:
  include: all
