site_name: Data pipeline

repo_name: owid/etl
repo_url: https://github.com/owid/etl

nav:
  - Home: "index.md"
  - Getting started:
    - Getting started: "getting-started/index.md"
    - Working environment: "getting-started/working-environment.md"
    - Building datasets: "getting-started/building-datasets.md"
    - Consuming datasets: "getting-started/consuming-datasets.md"
  - Tutorials:
    - Tutorials: "tutorials/index.md"
    - Adding data:
      - Adding data: "tutorials/adding-data/index.md"
      - Walkthrough: "tutorials/adding-data/walkthrough.md"
      - Manually add: "tutorials/adding-data/manual.md"
      - Fast-track: "tutorials/adding-data/fast-track.md"
    - Updating charts:
      - Submitting chart revisions: "tutorials/charts/updating-charts.md"
      - Reviewing chart revisions: "tutorials/charts/reviewing-charts.md"
      - Using chatGPT: "tutorials/charts/chatgpt.md"
    - Harmonize country names: "tutorials/harmonize-countries.md"
    - Metadata in data pages: "tutorials/metadata-play.md"
    - Backporting Grapher datasets to ETL: "tutorials/backport.md"
    - Importing a private dataset to ETL: "tutorials/private-import.md"
  - Architecture:
      - Architecture: architecture/index.md
      - Our journey: "architecture/our-journey.md"
      - Design principles:
        - Computational graph:
          - Computational graph: "architecture/design/compute-graph/index.md"
        - ETL model: "architecture/design/phases.md"
        - Data model: "architecture/design/common-format.md"
        - Features and constraints: "architecture/design/features-constraints.md"
        - The DAG: "architecture/design/dag.md"
        - The URI: "architecture/design/uri.md"
      - ETL steps:
        - ETL steps: "architecture/workflow/index.md"
        - Snapshot: "architecture/workflow/snapshot.md"
        - Meadow: "architecture/workflow/meadow.md"
        - Garden: "architecture/workflow/garden.md"
        - Grapher: "architecture/workflow/grapher.md"
        - Special steps:
          # - Special steps: "architecture/workflow/other-steps/index.md"
          - Explorers: "architecture/workflow/other-steps/explorers.md"
          - Backport: "architecture/workflow/other-steps/backport.md"
          - Open Numbers: "architecture/workflow/other-steps/open-numbers.md"
          - ETag: "architecture/workflow/other-steps/etag.md"
          - GitHub: "architecture/workflow/other-steps/github.md"
          - Private steps: "architecture/workflow/other-steps/private.md"
      - Metadata:
        - Metadata: "architecture/metadata/index.md"
        - Metadata fields: "architecture/metadata/fields.md"
        - Propagation of metadata: "architecture/metadata/propagation.md"
        - Using metadata: "architecture/metadata/using.md"
  - Dataset catalog:
    - Dataset catalog: "data/index.md"
    - Faostat: "data/faostat.md"
    - Regions: "data/regions.md"
  - API:
    - API: "api/index.md"
    - Python: "api/python.ipynb"
  - Development:
    - Development: "dev/index.md"
    - Documentation: "dev/docs.md"
  - Contributing: "contributing.md"

theme:
  # logo: assets/logo.png
  favicon: assets/images/favicon.png
  # icon:
    # logo: material/library-outline
  logo: "assets/site-logo.svg"
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue-grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue-grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Lato
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - content.tooltips
    # - navigation.expand
    # - navigation.sections
    # - toc.follow
    - navigation.top
  custom_dir: docs/overrides

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - mkdocs-jupyter:
      ignore_h1_titles: True
  - search

extra_css:
  - css/extra.css

extra:
  homepage: https://docs.owid.io/projects/etl
  generator: false
  social:
    # icons available listed: https://github.com/squidfunk/mkdocs-material/tree/master/material/.icons/fontawesome
    - icon: fontawesome/brands/github
      link: https://github.com/ourworldindata
    - icon: fontawesome/solid/globe
      link: https://ourworldindata.org
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ourworldindata
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/ourworldindata

copyright: Copyright &copy; 2023 Our World in Data
