title:
  title: Deaths from natural disasters
  title_variant: ""
default_selection:
  - World
topic_tags:
  - Natural Disasters
default_dimensions:
  type: all_stacked
  timespan: decadal
  metric: total_number
dimensions:
  - slug: type
    name: Disaster type
    choices:
      - slug: all_disasters
        name: All disasters
        description: Deaths caused by all disaster types, combined
        group: Aggregates
      - slug: all_stacked
        name: All disasters (by type)
        description: Deaths broken down by the disaster type
        group: Aggregates
      - slug: all_disasters_excluding_extreme_temperature
        name: All disasters (excluding extreme temperatures)
        description: Excludes deaths from extreme temperatures, which are very incomplete across regions and over time
        group: Aggregates
      - slug: drought
        name: Droughts
        description: Deaths caused by drought events
        group: Individual disaster types
      - slug: earthquake
        name: Earthquakes
        description: Deaths caused by earthquakes
        group: Individual disaster types
      - slug: volcanic_activity
        name: Volcanoes
        description: Deaths caused by volcanic activity
        group: Individual disaster types
      - slug: flood
        name: Floods
        description: Deaths caused by flooding
        group: Individual disaster types
      - slug: dry_mass_movement
        name: Mass movement (dry)
        description: Deaths caused by dry mass movements
        group: Individual disaster types
      - slug: extreme_weather
        name: Storms
        description: Deaths caused by storm and extreme weather events
        group: Individual disaster types
      - slug: wildfire
        name: Wildfires
        description: Deaths caused by wildfires
        group: Individual disaster types
      - slug: extreme_temperature
        name: Extreme temperatures
        description: Deaths caused by extreme hot and cold temperatures
        group: Individual disaster types
  - slug: timespan
    name: Timespan
    description: Decadal average or annual figures
    choices:
      - slug: decadal
        name: Decadal average
        description: Better for comparing trends over time as it's less sensitive to one-off events
      - slug: annual
        name: Annual
        description: Better for seeing rarer events with death tolls in every individual year
  - slug: metric
    name: Metric
    description: Total number of deaths, or adjusted for population
    choices:
      - slug: total_number
        name: Total number
        description: The total number of disaster deaths
      - slug: per_capita
        name: Per capita
        description: Adjusted for population. Better for comparing rates across countries, and changes over time
views: []
