title:
  title: Vaccination introduction
  title_variant: by vaccine
dimensions:
  - name: Vaccine
    slug: description
    choices:
      - slug: "aP (acellular pertussis) vaccine"
        name: "Acellular pertussis vaccine"
      - slug: "Hepatitis A vaccine"
        name: "Hepatitis A vaccine"
      - slug: "Hepatitis B vaccine"
        name: "Hepatitis B vaccine"
      - slug: "HepB birth dose"
        name: "Hepatitis B birth dose"
      - slug: "Hib (Haemophilus influenzae type B) vaccine"
        name: "Hib (Haemophilus influenzae type B) vaccine"
      - slug: "HPV (Human Papilloma Virus) vaccine"
        name: "HPV (Human Papilloma Virus) vaccine"
      - slug: "IPV (Inactivated polio vaccine)"
        name: "IPV (Inactivated polio vaccine)"
      - slug: "IPV (Inactivated polio vaccine) 2nd dose"
        name: "IPV (Inactivated polio vaccine) 2nd dose"
      - slug: "Japanese Encephalitis"
        name: "Japanese Encephalitis"
      - slug: "Malaria vaccine"
        name: "Malaria vaccine"
      - slug: "Measles-containing vaccine 2nd dose"
        name: "Measles-containing vaccine 2nd dose"
      - slug: "Meningococcal meningitis vaccines (all strains)"
        name: "Meningococcal meningitis vaccines (all strains)"
      - slug: "Mumps vaccine"
        name: "Mumps vaccine"
      - slug: "PCV (Pneumococcal conjugate vaccine)"
        name: "PCV (Pneumococcal conjugate vaccine)"
      - slug: "PPV (Pneumococcal polysaccharide vaccine)"
        name: "PPV (Pneumococcal polysaccharide vaccine)"
      - slug: "Rotavirus vaccine"
        name: "Rotavirus vaccine"
      - slug: "Rubella vaccine"
        name: "Rubella vaccine"
      - slug: "Seasonal Influenza vaccine"
        name: "Seasonal Influenza vaccine"
      - slug: "Typhoid"
        name: "Typhoid vaccine"
      - slug: "Varicella vaccine"
        name: "Chickenpox vaccine"
      - slug: "YF (Yellow fever) vaccine"
        name: "Yellow fever vaccine"
views: []
