config:
  explorerTitle: "Conflict Data Source"
  explorerSubtitle: "Explore the world's conflicts through the leading approaches to measuring them."
  isPublished: true
definitions:
  common_views:
    - config:
        yAxisMin: 0
        hideAnnotationFieldsInTitle: true
        chartTypes:
          - "LineChart"
          - "DiscreteBar"
dimensions:
  - slug: conflict_type
    name: "Conflict type"
    presentation:
      type: dropdown
    choices:
      - slug: interstate_conflicts
        name: "Interstate conflicts"
  - slug: measure
    name: "Measure"
    presentation:
      type: dropdown
    choices:
      - slug: conflict_deaths
        name: "Conflict deaths"
      - slug: number_of_conflicts
        name: "Number of conflicts"
      - slug: conflict_rate
        name: "Conflict rate"
      - slug: conflict_participants
        name: "Conflict participants"
  - slug: conflict_sub_type
    name: "Conflict sub-type"
    presentation:
      type: dropdown
    choices:
      - slug: na
        name: ""
      - slug: all_sub_types
        name: "All sub-types"
      - slug: by_sub_type
        name: "By sub-type"
      - slug: only_wars
        name: "Only wars"
  - slug: sub_measure
    name: "Sub-measure"
    presentation:
      type: dropdown
    choices:
      - slug: regional_data
        name: "Regional data"
      - slug: all_ongoing_conflicts
        name: "All ongoing conflicts"
      - slug: only_new_conflicts
        name: "Only new conflicts"
      - slug: country_level_data
        name: "Country-level data"
views:
  - dimensions:
      conflict_type: "interstate_conflicts"
      measure: "conflict_deaths"
      conflict_sub_type: "na"
      sub_measure: "regional_data"
    indicators:
      y:
        - catalogPath: "grapher/war/2023-09-21/cow_mid/cow_mid#number_ongoing_disputes__fatality_unknown__hostility_all"
        - catalogPath: "grapher/war/2023-09-21/cow_mid/cow_mid#number_ongoing_disputes__fatality_no_deaths__hostility_all"
        - catalogPath: "grapher/war/2023-09-21/cow_mid/cow_mid#number_ongoing_disputes__fatality_1_25_deaths__hostility_all"
        - catalogPath: "grapher/war/2023-09-21/cow_mid/cow_mid#number_ongoing_disputes__fatality_26_100_deaths__hostility_all"
        - catalogPath: "grapher/war/2023-09-21/cow_mid/cow_mid#number_ongoing_disputes__fatality_101_250_deaths__hostility_all"
        - catalogPath: "grapher/war/2023-09-21/cow_mid/cow_mid#number_ongoing_disputes__fatality_251_500_deaths__hostility_all"
        - catalogPath: "grapher/war/2023-09-21/cow_mid/cow_mid#number_ongoing_disputes__fatality_501_999_deaths__hostility_all"
        - catalogPath: "grapher/war/2023-09-21/cow_mid/cow_mid#number_ongoing_disputes__fatality__gt__999_deaths__hostility_all"
    config:
      title: "Deaths in interstate conflicts"
      subtitle: "Included are deaths of combatants due to fighting between states that year."
      chartTypes:
        - "StackedBar"
      baseColorScheme: "stackedAreaDefault"
      hideRelativeToggle: false
  - dimensions:
      conflict_type: "interstate_conflicts"
      measure: "number_of_conflicts"
      conflict_sub_type: "all_sub_types"
      sub_measure: "all_ongoing_conflicts"
    indicators:
      y:
        - catalogPath: "grapher/war/2023-09-21/cow_mid/cow_mid#number_ongoing_disputes__fatality_all__hostility_all"
    config:
      title: "Number of interstate conflicts"
      subtitle: "Included are conflicts between states where force was [threatened, displayed, used](#dod:force-cow), or escalated to a [war](#dod:interstate-war-cow) that year."
      note: "The number of states has increased a lot over time. Some conflicts affect several regions. The sum across all regions can therefore be higher than the global number."
  - dimensions:
      conflict_type: "interstate_conflicts"
      measure: "number_of_conflicts"
      conflict_sub_type: "by_sub_type"
      sub_measure: "all_ongoing_conflicts"
    indicators:
      y:
        - catalogPath: "grapher/war/2023-09-21/cow_mid/cow_mid#number_ongoing_disputes__fatality_all__hostility_threat_to_use_force"
        - catalogPath: "grapher/war/2023-09-21/cow_mid/cow_mid#number_ongoing_disputes__fatality_all__hostility_display_of_force"
        - catalogPath: "grapher/war/2023-09-21/cow_mid/cow_mid#number_ongoing_disputes__fatality_all__hostility_use_of_force"
        - catalogPath: "grapher/war/2023-09-21/cow_mid/cow_mid#number_ongoing_disputes__fatality_all__hostility_war"
    config:
      title: "Number of interstate conflicts"
      subtitle: "Included are conflicts between states where force was [threatened, displayed, used](#dod:force-cow), or escalated to a [war](#dod:interstate-war-cow) that year."
      note: "The number of states has increased a lot over time. Some conflicts affect several regions. The sum across all regions can therefore be higher than the global number."
      chartTypes:
        - "StackedBar"
      baseColorScheme: "stackedAreaDefault"
      hideRelativeToggle: false
  - dimensions:
      conflict_type: "interstate_conflicts"
      measure: "number_of_conflicts"
      conflict_sub_type: "only_wars"
      sub_measure: "all_ongoing_conflicts"
    indicators:
      y:
        - catalogPath: "grapher/war/2023-09-21/cow_mid/cow_mid#number_ongoing_disputes__fatality_all__hostility_war"
    config:
      title: "Number of interstate wars"
      subtitle: "Included are [interstate wars](#dod:interstate-war-cow) that were ongoing that year."
      note: "Some wars affect several regions. The sum across all regions can therefore be higher than the global number."
  - dimensions:
      conflict_type: "interstate_conflicts"
      measure: "number_of_conflicts"
      conflict_sub_type: "all_sub_types"
      sub_measure: "only_new_conflicts"
    indicators:
      y:
        - catalogPath: "grapher/war/2023-09-21/cow_mid/cow_mid#number_new_disputes__fatality_all__hostility_all"
    config:
      title: "Number of new interstate conflicts"
      subtitle: "Included are conflicts between states where force was [threatened, displayed, used](#dod:force-cow), or escalated to a [war](#dod:interstate-war-cow) that year for the first time."
  - dimensions:
      conflict_type: "interstate_conflicts"
      measure: "number_of_conflicts"
      conflict_sub_type: "by_sub_type"
      sub_measure: "only_new_conflicts"
    indicators:
      y:
        - catalogPath: "grapher/war/2023-09-21/cow_mid/cow_mid#number_new_disputes__fatality_all__hostility_threat_to_use_force"
        - catalogPath: "grapher/war/2023-09-21/cow_mid/cow_mid#number_new_disputes__fatality_all__hostility_display_of_force"
        - catalogPath: "grapher/war/2023-09-21/cow_mid/cow_mid#number_new_disputes__fatality_all__hostility_use_of_force"
        - catalogPath: "grapher/war/2023-09-21/cow_mid/cow_mid#number_new_disputes__fatality_all__hostility_war"
    config:
      title: "Number of new intrastate conflicts"
      subtitle: "Included are conflicts between states where force was [threatened, displayed, used](#dod:force-cow), or escalated to a [war](#dod:interstate-war-cow) that year for the first time."
      note: "Some conflicts affect several regions, and do not necessarily start at the same time across them. The sum across all regions can therefore be higher than the global number."
      chartTypes:
        - "StackedBar"
      baseColorScheme: "stackedAreaDefault"
      hideRelativeToggle: false
  - dimensions:
      conflict_type: "interstate_conflicts"
      measure: "number_of_conflicts"
      conflict_sub_type: "only_wars"
      sub_measure: "only_new_conflicts"
    indicators:
      y:
        - catalogPath: "grapher/war/2023-09-21/cow_mid/cow_mid#number_new_disputes__fatality_all__hostility_war"
    config:
      title: "Number of new interstate wars"
      subtitle: "Included are [interstate wars](#dod:interstate-war-cow) that started that year."
  - dimensions:
      conflict_type: "interstate_conflicts"
      measure: "conflict_rate"
      conflict_sub_type: "all_sub_types"
      sub_measure: "all_ongoing_conflicts"
    indicators:
      y:
        - catalogPath: "grapher/war/2023-09-21/cow_mid/cow_mid#number_ongoing_disputes_per_country_pair__fatality_all__hostility_all"
    config:
      title: "Rate of interstate conflicts"
      subtitle: "The number of conflicts divided by the number of all state-pairs. This accounts for the changing number of states over time. Included are conflicts between states where force was [threatened, displayed, used](#dod:force-cow), or escalated to a [war](#dod:interstate-war-cow) that year."
  - dimensions:
      conflict_type: "interstate_conflicts"
      measure: "conflict_rate"
      conflict_sub_type: "by_sub_type"
      sub_measure: "all_ongoing_conflicts"
    indicators:
      y:
        - catalogPath: "grapher/war/2023-09-21/cow_mid/cow_mid#number_ongoing_disputes_per_country_pair__fatality_all__hostility_threat_to_use_force"
        - catalogPath: "grapher/war/2023-09-21/cow_mid/cow_mid#number_ongoing_disputes_per_country_pair__fatality_all__hostility_display_of_force"
        - catalogPath: "grapher/war/2023-09-21/cow_mid/cow_mid#number_ongoing_disputes_per_country_pair__fatality_all__hostility_use_of_force"
        - catalogPath: "grapher/war/2023-09-21/cow_mid/cow_mid#number_ongoing_disputes_per_country_pair__fatality_all__hostility_war"
    config:
      title: "Rate of interstate conflicts"
      subtitle: "The number of conflicts divided by the number of all state-pairs. This accounts for the changing number of states over time. Included are conflicts between states where force was [threatened, displayed, used](#dod:force-cow), or escalated to a [war](#dod:interstate-war-cow) that year."
      note: "Some conflicts affect several regions. The sum across all regions can therefore be higher than the global number."
      chartTypes:
        - "StackedBar"
      baseColorScheme: "stackedAreaDefault"
      hideRelativeToggle: false
  - dimensions:
      conflict_type: "interstate_conflicts"
      measure: "conflict_rate"
      conflict_sub_type: "only_wars"
      sub_measure: "all_ongoing_conflicts"
    indicators:
      y:
        - catalogPath: "grapher/war/2023-09-21/cow_mid/cow_mid#number_ongoing_disputes_per_country_pair__fatality_all__hostility_war"
    config:
      title: "Rate of interstate wars"
      subtitle: "The number of wars divided by the number of all state-pairs. This accounts for the changing number of states over time. Included are [interstate wars](#dod:interstate-war-cow) that were ongoing that year."
  - dimensions:
      conflict_type: "interstate_conflicts"
      measure: "conflict_rate"
      conflict_sub_type: "all_sub_types"
      sub_measure: "only_new_conflicts"
    indicators:
      y:
        - catalogPath: "grapher/war/2023-09-21/cow_mid/cow_mid#number_new_disputes_per_country_pair__fatality_all__hostility_all"
    config:
      title: "Rate of new interstate conflicts"
      subtitle: "The number of conflicts divided by the number of all state-pairs. This accounts for the changing number of states over time. Included are conflicts between states where force was [threatened, displayed, used](#dod:force-cow), or escalated to a [war](#dod:interstate-war-cow) that year for the first time."
  - dimensions:
      conflict_type: "interstate_conflicts"
      measure: "conflict_rate"
      conflict_sub_type: "by_sub_type"
      sub_measure: "only_new_conflicts"
    indicators:
      y:
        - catalogPath: "grapher/war/2023-09-21/cow_mid/cow_mid#number_new_disputes_per_country_pair__fatality_all__hostility_threat_to_use_force"
        - catalogPath: "grapher/war/2023-09-21/cow_mid/cow_mid#number_new_disputes_per_country_pair__fatality_all__hostility_display_of_force"
        - catalogPath: "grapher/war/2023-09-21/cow_mid/cow_mid#number_new_disputes_per_country_pair__fatality_all__hostility_use_of_force"
        - catalogPath: "grapher/war/2023-09-21/cow_mid/cow_mid#number_new_disputes_per_country_pair__fatality_all__hostility_war"
    config:
      title: "Rate of new interstate conflicts"
      subtitle: "The number of conflicts divided by the number of all state-pairs. This accounts for the changing number of states over time. Included are conflicts between states where force was [threatened, displayed, used](#dod:force-cow), or escalated to a [war](#dod:interstate-war-cow) that year for the first time."
      note: "Some conflicts affect several regions, and do not necessarily start at the same time across them. The sum across all regions can therefore be higher than the global number."
      chartTypes:
        - "StackedBar"
      baseColorScheme: "stackedAreaDefault"
      hideRelativeToggle: false
  - dimensions:
      conflict_type: "interstate_conflicts"
      measure: "conflict_rate"
      conflict_sub_type: "only_wars"
      sub_measure: "only_new_conflicts"
    indicators:
      y:
        - catalogPath: "grapher/war/2023-09-21/cow_mid/cow_mid#number_new_disputes_per_country_pair__fatality_all__hostility_war"
    config:
      title: "Rate of new interstate wars"
      subtitle: "The number of wars divided by the number of all state-pairs. This accounts for the changing number of states over time. Included are [interstate wars](#dod:interstate-war-cow) that started that year."
  - dimensions:
      conflict_type: "interstate_conflicts"
      measure: "conflict_participants"
      conflict_sub_type: "na"
      sub_measure: "regional_data"
    indicators:
      y:
        - catalogPath: "grapher/war/2023-09-21/cow_mid/cow_mid_country#number_participants__hostlev_all"
    config:
      title: "Number of states involved in interstate conflicts"
      subtitle: "Included are states that participated in at least one conflict with another state where force was [threatened, displayed, or used](#dod:force-mic) that year."
  - dimensions:
      conflict_type: "interstate_conflicts"
      measure: "conflict_participants"
      conflict_sub_type: "na"
      sub_measure: "country_level_data"
    indicators:
      y:
        - catalogPath: "grapher/war/2023-09-21/cow_mid/cow_mid_country#participated_in_conflict__hostlev_all"
    config:
      title: "States involved in interstate conflicts"
      subtitle: "Included are states that participated in at least one conflict with another state where force was [threatened, displayed, or used](#dod:force-mic) that year."
      note: "Some states are not shown in the map because they do not exist anymore."
      hasMapTab: true
      tab: "map"
      selectedFacetStrategy: "entity"
