config:
  explorerTitle: "Conflict Data Source"
  explorerSubtitle: "Explore the world's conflicts through the leading approaches to measuring them."
  isPublished: true
definitions:
  common_views:
    - config:
        yAxisMin: 0
        hideAnnotationFieldsInTitle: true
        chartTypes:
          - "LineChart"
          - "DiscreteBar"
dimensions:
  - slug: conflict_type
    name: "Conflict type"
    presentation:
      type: dropdown
    choices:
      - slug: all_state_based_conflicts
        name: "All state-based conflicts"
      - slug: interstate_conflicts
        name: "Interstate conflicts"
      - slug: intrastate_conflicts
        name: "Intrastate conflicts"
      - slug: extrastate_conflicts
        name: "Extrastate conflicts"
  - slug: measure
    name: "Measure"
    presentation:
      type: dropdown
    choices:
      - slug: conflict_deaths
        name: "Conflict deaths"
      - slug: death_rate
        name: "Death rate"
  - slug: conflict_sub_type
    name: "Conflict sub-type"
    presentation:
      type: dropdown
    choices:
      - slug: na
        name: ""
      - slug: all_sub_types
        name: "All sub-types"
      - slug: by_sub_type
        name: "By sub-type"
      - slug: only_non_internationalized_conflicts
        name: "Only non-internationalized conflicts"
      - slug: only_internationalized_conflicts
        name: "Only internationalized conflicts"
  - slug: sub_measure
    name: "Sub-measure"
    presentation:
      type: dropdown
    choices:
      - slug: na
        name: ""
      - slug: regional_data
        name: "Regional data"
views:
  - dimensions:
      conflict_type: "all_state_based_conflicts"
      measure: "conflict_deaths"
      conflict_sub_type: "all_sub_types"
      sub_measure: "regional_data"
    indicators:
      y:
        - catalogPath: "grapher/war/2025-06-16/ucdp_prio/ucdp_prio#number_deaths_ongoing_conflicts_low__conflict_type_state_based"
        - catalogPath: "grapher/war/2025-06-16/ucdp_prio/ucdp_prio#number_deaths_ongoing_conflicts__conflict_type_state_based"
        - catalogPath: "grapher/war/2025-06-16/ucdp_prio/ucdp_prio#number_deaths_ongoing_conflicts_high__conflict_type_state_based"
    config:
      title: "Deaths in state-based conflicts"
      subtitle: "Included are deaths of combatants and civilians due to fighting in [interstate](#dod:interstate-ucdp), [intrastate](#dod:intrastate-ucdp), and [extrasystemic](#dod:extrasystemic-ucdp) conflicts that were ongoing that year."
      note: "'Best' estimates as identified by UCDP."
      selectedFacetStrategy: "entity"
  - dimensions:
      conflict_type: "all_state_based_conflicts"
      measure: "conflict_deaths"
      conflict_sub_type: "by_sub_type"
      sub_measure: "regional_data"
    indicators:
      y:
        - catalogPath: "grapher/war/2025-06-16/ucdp_prio/ucdp_prio#number_deaths_ongoing_conflicts__conflict_type_intrastate__internationalized"
        - catalogPath: "grapher/war/2025-06-16/ucdp_prio/ucdp_prio#number_deaths_ongoing_conflicts__conflict_type_intrastate__non_internationalized"
        - catalogPath: "grapher/war/2025-06-16/ucdp_prio/ucdp_prio#number_deaths_ongoing_conflicts__conflict_type_extrasystemic"
        - catalogPath: "grapher/war/2025-06-16/ucdp_prio/ucdp_prio#number_deaths_ongoing_conflicts__conflict_type_interstate"
    config:
      title: "Deaths in state-based conflicts"
      subtitle: "Included are deaths of combatants and civilians due to fighting in [interstate](#dod:interstate-ucdp), [intrastate](#dod:intrastate-ucdp), and [extrasystemic](#dod:extrasystemic-ucdp) conflicts that were ongoing that year."
      chartTypes:
        - "StackedBar"
      baseColorScheme: "stackedAreaDefault"
      hideRelativeToggle: false
  - dimensions:
      conflict_type: "all_state_based_conflicts"
      measure: "death_rate"
      conflict_sub_type: "all_sub_types"
      sub_measure: "regional_data"
    indicators:
      y:
        - catalogPath: "grapher/war/2025-06-16/ucdp_prio/ucdp_prio#number_deaths_ongoing_conflicts_low_per_capita__conflict_type_state_based"
        - catalogPath: "grapher/war/2025-06-16/ucdp_prio/ucdp_prio#number_deaths_ongoing_conflicts_per_capita__conflict_type_state_based"
        - catalogPath: "grapher/war/2025-06-16/ucdp_prio/ucdp_prio#number_deaths_ongoing_conflicts_high_per_capita__conflict_type_state_based"
    config:
      title: "Death rate in state-based conflicts"
      subtitle: "Deaths of combatants and civilians due to fighting, per 100,000 people. Included are [interstate](#dod:interstate-ucdp), [intrastate](#dod:intrastate-ucdp), and [extrasystemic](#dod:extrasystemic-ucdp) conflicts that were ongoing that year."
      note: "'Best' estimates as identified by UCDP."
      selectedFacetStrategy: "entity"
  - dimensions:
      conflict_type: "all_state_based_conflicts"
      measure: "death_rate"
      conflict_sub_type: "by_sub_type"
      sub_measure: "regional_data"
    indicators:
      y:
        - catalogPath: "grapher/war/2025-06-16/ucdp_prio/ucdp_prio#number_deaths_ongoing_conflicts_per_capita__conflict_type_intrastate__internationalized"
        - catalogPath: "grapher/war/2025-06-16/ucdp_prio/ucdp_prio#number_deaths_ongoing_conflicts_per_capita__conflict_type_intrastate__non_internationalized"
        - catalogPath: "grapher/war/2025-06-16/ucdp_prio/ucdp_prio#number_deaths_ongoing_conflicts_per_capita__conflict_type_extrasystemic"
        - catalogPath: "grapher/war/2025-06-16/ucdp_prio/ucdp_prio#number_deaths_ongoing_conflicts_per_capita__conflict_type_interstate"
    config:
      title: "Death rate in state-based conflicts"
      subtitle: "Deaths of combatants and civilians due to fighting, per 100,000 people. Included are [interstate](#dod:interstate-ucdp), [intrastate](#dod:intrastate-ucdp), and [extrasystemic](#dod:extrasystemic-ucdp) conflicts that were ongoing that year."
      chartTypes:
        - "StackedBar"
      baseColorScheme: "stackedAreaDefault"
      hideRelativeToggle: false
  - dimensions:
      conflict_type: "interstate_conflicts"
      measure: "conflict_deaths"
      conflict_sub_type: "na"
      sub_measure: "regional_data"
    indicators:
      y:
        - catalogPath: "grapher/war/2025-06-16/ucdp_prio/ucdp_prio#number_deaths_ongoing_conflicts_low__conflict_type_interstate"
        - catalogPath: "grapher/war/2025-06-16/ucdp_prio/ucdp_prio#number_deaths_ongoing_conflicts_high__conflict_type_interstate"
    config:
      title: "Deaths in interstate conflicts"
      subtitle: "Included are deaths of combatants and civilians due to fighting in [interstate conflicts](#dod:interstate-ucdp) that were ongoing that year."
      note: "'Best' estimates as identified by UCDP."
      selectedFacetStrategy: "entity"
  - dimensions:
      conflict_type: "interstate_conflicts"
      measure: "death_rate"
      conflict_sub_type: "na"
      sub_measure: "regional_data"
    indicators:
      y:
        - catalogPath: "grapher/war/2025-06-16/ucdp_prio/ucdp_prio#number_deaths_ongoing_conflicts_low_per_capita__conflict_type_interstate"
        - catalogPath: "grapher/war/2025-06-16/ucdp_prio/ucdp_prio#number_deaths_ongoing_conflicts_high_per_capita__conflict_type_interstate"
    config:
      title: "Death rate in interstate conflicts"
      subtitle: "Deaths of combatants and civilians due to fighting, per 100,000 people. Included are [interstate conflicts](#dod:interstate-ucdp) that were ongoing that year."
      note: "'Best' estimates as identified by UCDP."
      selectedFacetStrategy: "entity"
  - dimensions:
      conflict_type: "intrastate_conflicts"
      measure: "conflict_deaths"
      conflict_sub_type: "all_sub_types"
      sub_measure: "regional_data"
    indicators:
      y:
        - catalogPath: "grapher/war/2025-06-16/ucdp_prio/ucdp_prio#number_deaths_ongoing_conflicts_low__conflict_type_intrastate"
        - catalogPath: "grapher/war/2025-06-16/ucdp_prio/ucdp_prio#number_deaths_ongoing_conflicts__conflict_type_intrastate"
        - catalogPath: "grapher/war/2025-06-16/ucdp_prio/ucdp_prio#number_deaths_ongoing_conflicts_high__conflict_type_intrastate"
    config:
      title: "Deaths in intrastate conflicts"
      subtitle: "Included are deaths of combatants and civilians due to fighting in [intrastate conflicts](#dod:intrastate-ucdp) that were ongoing that year."
      note: "'Best' estimates as identified by UCDP."
      selectedFacetStrategy: "entity"
  - dimensions:
      conflict_type: "intrastate_conflicts"
      measure: "conflict_deaths"
      conflict_sub_type: "only_non_internationalized_conflicts"
      sub_measure: "na"
    indicators:
      y:
        - catalogPath: "grapher/war/2025-06-16/ucdp_prio/ucdp_prio#number_deaths_ongoing_conflicts_low__conflict_type_intrastate__non_internationalized"
        - catalogPath: "grapher/war/2025-06-16/ucdp_prio/ucdp_prio#number_deaths_ongoing_conflicts_high__conflict_type_intrastate__non_internationalized"
    config:
      title: "Deaths in non-internationalized intrastate conflicts"
      subtitle: "Included are deaths of combatants and civilians due to fighting in [non-internationalized intrastate conflicts](#dod:intrastate-ucdp) that were ongoing that year."
      note: "'Best' estimates as identified by UCDP."
      selectedFacetStrategy: "entity"
  - dimensions:
      conflict_type: "intrastate_conflicts"
      measure: "conflict_deaths"
      conflict_sub_type: "only_internationalized_conflicts"
      sub_measure: "na"
    indicators:
      y:
        - catalogPath: "grapher/war/2025-06-16/ucdp_prio/ucdp_prio#number_deaths_ongoing_conflicts_low__conflict_type_intrastate__internationalized"
        - catalogPath: "grapher/war/2025-06-16/ucdp_prio/ucdp_prio#number_deaths_ongoing_conflicts_high__conflict_type_intrastate__internationalized"
    config:
      title: "Deaths in internationalized intrastate conflicts"
      subtitle: "Included are deaths of combatants and civilians due to fighting in [internationalized intrastate conflicts](#dod:intrastate-ucdp) that were ongoing that year."
      note: "'Best' estimates as identified by UCDP."
      selectedFacetStrategy: "entity"
  - dimensions:
      conflict_type: "intrastate_conflicts"
      measure: "death_rate"
      conflict_sub_type: "all_sub_types"
      sub_measure: "regional_data"
    indicators:
      y:
        - catalogPath: "grapher/war/2025-06-16/ucdp_prio/ucdp_prio#number_deaths_ongoing_conflicts_high_per_capita__conflict_type_intrastate"
        - catalogPath: "grapher/war/2025-06-16/ucdp_prio/ucdp_prio#number_deaths_ongoing_conflicts_per_capita__conflict_type_intrastate"
        - catalogPath: "grapher/war/2025-06-16/ucdp_prio/ucdp_prio#number_deaths_ongoing_conflicts_low_per_capita__conflict_type_intrastate"
    config:
      title: "Death rate in intrastate conflicts"
      subtitle: "Deaths of combatants and civilians due to fighting, per 100,000 people. Included are [intrastate conflicts](#dod:intrastate-ucdp) that were ongoing that year."
      note: "'Best' estimates as identified by UCDP."
      selectedFacetStrategy: "entity"
  - dimensions:
      conflict_type: "intrastate_conflicts"
      measure: "death_rate"
      conflict_sub_type: "only_non_internationalized_conflicts"
      sub_measure: "na"
    indicators:
      y:
        - catalogPath: "grapher/war/2025-06-16/ucdp_prio/ucdp_prio#number_deaths_ongoing_conflicts_low_per_capita__conflict_type_intrastate__non_internationalized"
        - catalogPath: "grapher/war/2025-06-16/ucdp_prio/ucdp_prio#number_deaths_ongoing_conflicts_high_per_capita__conflict_type_intrastate__non_internationalized"
    config:
      title: "Death rate in non-internationalized intrastate conflicts"
      subtitle: "Deaths of combatants and civilians due to fighting, per 100,000 people. Included are [non-internationalized intrastate conflicts](#dod:intrastate-ucdp) that were ongoing that year."
      note: "'Best' estimates as identified by UCDP."
      selectedFacetStrategy: "entity"
  - dimensions:
      conflict_type: "intrastate_conflicts"
      measure: "death_rate"
      conflict_sub_type: "only_internationalized_conflicts"
      sub_measure: "na"
    indicators:
      y:
        - catalogPath: "grapher/war/2025-06-16/ucdp_prio/ucdp_prio#number_deaths_ongoing_conflicts_low_per_capita__conflict_type_intrastate__internationalized"
        - catalogPath: "grapher/war/2025-06-16/ucdp_prio/ucdp_prio#number_deaths_ongoing_conflicts_high_per_capita__conflict_type_intrastate__internationalized"
    config:
      title: "Death rate in internationalized intrastate conflicts"
      subtitle: "Deaths of combatants and civilians due to fighting, per 100,000 people. Included are [internationalized intrastate conflicts](#dod:intrastate-ucdp) that were ongoing that year."
      note: "'Best' estimates as identified by UCDP."
      selectedFacetStrategy: "entity"
  - dimensions:
      conflict_type: "extrastate_conflicts"
      measure: "conflict_deaths"
      conflict_sub_type: "na"
      sub_measure: "regional_data"
    indicators:
      y:
        - catalogPath: "grapher/war/2025-06-16/ucdp_prio/ucdp_prio#number_deaths_ongoing_conflicts_low__conflict_type_extrasystemic"
        - catalogPath: "grapher/war/2025-06-16/ucdp_prio/ucdp_prio#number_deaths_ongoing_conflicts_high__conflict_type_extrasystemic"
    config:
      title: "Deaths in extrasystemic conflicts"
      subtitle: "Included are deaths of combatants and civilians due to fighting in [extrasystemic conflicts](#dod:extrasystemic-ucdp) that were ongoing that year."
      note: "'Best' estimates as identified by UCDP."
      selectedFacetStrategy: "entity"
  - dimensions:
      conflict_type: "extrastate_conflicts"
      measure: "death_rate"
      conflict_sub_type: "na"
      sub_measure: "regional_data"
    indicators:
      y:
        - catalogPath: "grapher/war/2025-06-16/ucdp_prio/ucdp_prio#number_deaths_ongoing_conflicts_low_per_capita__conflict_type_extrasystemic"
        - catalogPath: "grapher/war/2025-06-16/ucdp_prio/ucdp_prio#number_deaths_ongoing_conflicts_high_per_capita__conflict_type_extrasystemic"
    config:
      title: "Death rate in extrasystemic conflicts"
      subtitle: "Deaths of combatants and civilians due to fighting, per 100,000 people. Included are [extrasystemic conflicts](#dod:extrasystemic-ucdp) that were ongoing that year."
      note: "'Best' estimates as identified by UCDP."
      selectedFacetStrategy: "entity"
