# This file would be autogenerated by a script that would parse the DAG and generate the TypedDicts.
# Every time the DAG is modified, this file would be regenerated by a tool.
from typing import TypedDict, Callable
from owid import catalog

# This typed dict enumerates the direct upstream dependencies of the combined dataset.
# When one of the keys are accessed, the returned value is a loader function for that dataset.
# One such type would exist for every dataset in the DAG.
Deps_garden__ember__2022_08_01__combined_electricity_review = TypedDict('Deps_garden__ember__2022_08_01__combined_electricity_review', {
    'garden/ember/2022-08-01/european_electricity_review': Callable[[], catalog.Dataset],
    'garden/ember/2022-08-01/global_electricity_review': Callable[[], catalog.Dataset]
    })

# The full typed dag. For every dataset there would be a key in this (large) typed dict.
TypedDag = TypedDict('TypedDag', {
    'garden/ember/2022-08-01/combined_electricity_review': Deps_garden__ember__2022_08_01__combined_electricity_review,
    })

# The concrete value that is used by code to use at runtime that has the loader
# functions filled in
full_typed_dag : TypedDag = {
    'garden/ember/2022-08-01/combined_electricity_review': {
        'garden/ember/2022-08-01/european_electricity_review': lambda: catalog.Dataset('garden/ember/2022-08-01/european_electricity_review'),
        'garden/ember/2022-08-01/global_electricity_review': lambda: catalog.Dataset('garden/ember/2022-08-01/global_electricity_review')
    }
}

# Maybe we'll want some convenience names for which we would get autocompletion. Note
# that these values can be used interchangeably with the string values that they hold
# for access of the TypedDag typed dict above. This block is optional.
garden__ember__2022_08_01__combined_electricity_review = 'garden/ember/2022-08-01/combined_electricity_review'
garden__ember__2022_08_01__european_electricity_review = 'garden/ember/2022-08-01/european_electricity_review'
garden__ember__2022_08_01__global_electricity_review = 'garden/ember/2022-08-01/global_electricity_review'
