config:
  explorerTitle: "COVID-19"
  explorerSubtitle: "Explore global data on COVID-19."
  selection:
    - United States
    - Brazil
    - Japan
    - Germany
  downloadDataLink: "https://docs.owid.io/projects/etl/api/covid/"
  subNavId: "coronavirus"
  subNavCurrentId: "data-explorer"
  wpBlockId: 43869
  hasMapTab: "true"
  yAxisMin: 0
  thumbnail: "https://ourworldindata.org/coronavirus-data-explorer.png"
  isPublished: "true"

dimensions:
  - slug: metric
    name: Metric
    choices:
      - slug: xm
        name: Excess mortality (%)
      - slug: xm_count
        name: Excess mortality (count)
    presentation:
      type: dropdown
  - slug: interval
    name: Interval
    choices:
      - slug: weekly
        name: Weekly
      - slug: cum
        name: Cumulative
    presentation:
      type: dropdown
  - slug: relative
    name: Relative to population
    presentation:
      type: checkbox

views:
  #######################
  # Excess mortality (count)
  #######################
  - dimensions:
      metric: xm_count
      interval: cum
      relative: false
    indicators:
      y: excess_mortality#cum_excess_proj_all_ages

  - dimensions:
      metric: xm_count
      interval: cum
      relative: true
    indicators:
      y: excess_mortality#cum_excess_per_million_proj_all_ages

  #######################
  # Excess mortality (%)
  #######################
  - dimensions:
      metric: xm
      interval: cum
      relative: false
    indicators:
      y: excess_mortality#cum_p_proj_all_ages
  - dimensions:
      metric: xm
      interval: weekly
      relative: false
    indicators:
      y: excess_mortality#p_proj_all_ages
