from pathlib import Path

from etl.paths import BASE_DIR

WIZARD_CFG_NAME = ".wizardcfg"

# PATH TO WIZARD CONFIG FOLDER
WIZARD_CFG = BASE_DIR / WIZARD_CFG_NAME

# PATH TO WIZARD ANOMALIES
WIZARD_ANOMALIES_RELATIVE = Path(WIZARD_CFG_NAME) / "anomalies"
WIZARD_ANOMALIES = WIZARD_CFG / "anomalies"
