steps:
  # UNEP Consumption of controlled substances
  data://grapher/unep/2023-03-17/consumption_controlled_substances:
    - data://garden/unep/2023-03-17/consumption_controlled_substances:
      - data://meadow/unep/2023-03-17/consumption_controlled_substances:
        - snapshot://unep/2023-03-17/consumption_controlled_substances_bromochloromethane.xlsx
        - snapshot://unep/2023-03-17/consumption_controlled_substances_carbon_tetrachloride.xlsx
        - snapshot://unep/2023-03-17/consumption_controlled_substances_chlorofluorocarbons.xlsx
        - snapshot://unep/2023-03-17/consumption_controlled_substances_halons.xlsx
        - snapshot://unep/2023-03-17/consumption_controlled_substances_hydrobromofluorocarbons.xlsx
        - snapshot://unep/2023-03-17/consumption_controlled_substances_hydrochlorofluorocarbons.xlsx
        - snapshot://unep/2023-03-17/consumption_controlled_substances_hydrofluorocarbons.xlsx
        - snapshot://unep/2023-03-17/consumption_controlled_substances_methyl_bromide.xlsx
        - snapshot://unep/2023-03-17/consumption_controlled_substances_methyl_chloroform.xlsx
        - snapshot://unep/2023-03-17/consumption_controlled_substances_other_fully_halogenated.xlsx
      - data://garden/demography/2023-03-31/population
