title:
  title: Children out of school
  title_variant: by level of education and gender
topic_tags:
  - Global Education
default_selection:
  - Egypt
  - Niger
  - United Kingdom
  - Peru

dimensions:
  - name: Metric
    slug: metric_type
    choices:
      - slug: rate
        name: Share (%)
        description: Percentage of children out of school in the relevant age group
      - slug: number
        name: Number
        description: Total number of children out of school

  - name: Education level
    slug: level
    choices:
      - slug: pre_primary
        name: Pre-primary education
        description: Children one year before official primary entry age (typically age 5) who are not enrolled in school
      - slug: primary
        name: Primary education
        description: Children of primary school age (typically 6-11 years) who are not enrolled in school
      - slug: lower_secondary
        name: Lower secondary education
        description: Children of lower secondary school age (typically 12-14 years) who are not enrolled in school
      - slug: upper_secondary
        name: Upper secondary education
        description: Children of upper secondary school age (typically 15-17 years) who are not enrolled in school
      - slug: level_side_by_side
        name: All education levels
        description: Compare school participation across different levels of education

  - name: Gender
    slug: sex
    choices:
      - slug: both
        name: Both genders
      - slug: male
        name: Boys
      - slug: female
        name: Girls
      - slug: sex_side_by_side
        name: Girls vs. boys
        description: Compare school participation between girls and boys

views: []