title:
  title: PISA performance scores
  title_variant: by subject and gender
default_selection:
  - Finland
  - Singapore
  - South Korea
  - Canada

dimensions:
  - slug: subject
    name: Subject
    choices:
      - slug: mathematics
        name: Mathematics
        description: PISA mathematics scores measuring mathematical literacy and problem-solving skills.
      - slug: science
        name: Science
        description: PISA science scores measuring scientific literacy and understanding.
      - slug: reading
        name: Reading
        description: PISA reading scores measuring reading comprehension and literacy skills.
      - slug: subject_side_by_side
        name: All subjects
        description: Compare PISA performance across mathematics, science, and reading.

  - slug: sex
    name: Gender
    choices:
      - slug: both
        name: Both genders
        description: PISA performance for all students regardless of gender.
      - slug: girls
        name: Girls
        description: PISA performance among female students.
      - slug: boys
        name: Boys
        description: PISA performance among male students.
      - slug: sex_side_by_side
        name: Boys and girls
        description: Compare PISA performance between genders.

views: []