title:
  title: Share of teachers who are women
  title_variant: by level of education
default_selection:
  - Egypt
  - Niger
  - United Kingdom
  - Peru

dimensions:
  - name: Education level
    slug: level
    choices:
      - slug: primary
        name: Primary education
        description: Percentage of teachers who are women in primary education (typically ages 6-11).
      - slug: secondary
        name: Secondary education
        description: Percentage of teachers who are women in secondary education (typically ages 12-17).
      - slug: tertiary
        name: Tertiary education
        description: Percentage of teachers who are women in tertiary education (higher education).
      - slug: level_side_by_side
        name: All education levels
        description: Compare the share of women teachers across different education levels.

views: []