"""This script has been autogenerated by `walkthrough snapshot`."""

import pathlib

import click

from etl.snapshot import Snapshot

CURRENT_DIR = pathlib.Path(__file__).parent


@click.command()
@click.option(
    "--upload/--skip-upload",
    default=True,
    type=bool,
    help="Upload dataset to Walden",
)
def main(upload: bool) -> None:
<<<<<<< HEAD
    snap = Snapshot(CURRENT_DIR / "dummy.xlsx")
=======
    snap = Snapshot("dummy/2020-01-01/dummy.xlsx")
>>>>>>> fc256ac5a0f3c030e6053ca16acfec4070e07e66
    snap.download_from_source()
    snap.dvc_add(upload=upload)


if __name__ == "__main__":
    main()
