# Stub file for backwards compatibility - re-exports from core/processing.py
# New code should import from owid.catalog.core.processing
"""Common operations performed on tables and variables."""

from owid.catalog.core.processing import (
    ExcelFile,
    concat,
    ignore_warnings,
    keep_metadata,
    melt,
    merge,
    multi_merge,
    pivot,
    read_csv,
    read_custom,
    read_df,
    read_excel,
    read_feather,
    read_from_df,
    read_from_dict,
    read_from_records,
    read_fwf,
    read_json,
    read_parquet,
    read_rda,
    read_rds,
    read_stata,
    to_datetime,
    to_numeric,
)

__all__ = [
    "ExcelFile",
    "concat",
    "ignore_warnings",
    "keep_metadata",
    "melt",
    "merge",
    "multi_merge",
    "pivot",
    "read_csv",
    "read_custom",
    "read_df",
    "read_excel",
    "read_feather",
    "read_from_df",
    "read_from_dict",
    "read_from_records",
    "read_fwf",
    "read_json",
    "read_parquet",
    "read_rda",
    "read_rds",
    "read_stata",
    "to_datetime",
    "to_numeric",
]
