# Stub file for backwards compatibility - re-exports from core/indicators.py
# New code should import from owid.catalog.core.indicators and use Indicator class
# Variable is a backwards-compatible alias for Indicator
from owid.catalog.core.indicators import (
    METADATA_FIELDS,
    OPERATION,
    UNNAMED_INDICATOR,
    UNNAMED_VARIABLE,
    Indicator,
    IndicatorRolling,
    Variable,
    VariableRolling,
    combine_indicators_display,
    combine_indicators_metadata,
    combine_indicators_presentation,
    combine_indicators_processing_level,
    combine_indicators_processing_logs,
    combine_indicators_sort,
    combine_variables_display,
    combine_variables_metadata,
    combine_variables_presentation,
    combine_variables_processing_level,
    combine_variables_processing_logs,
    combine_variables_sort,
    copy_metadata,
    get_unique_description_key_points_from_indicators,
    get_unique_description_key_points_from_variables,
    get_unique_licenses_from_indicators,
    get_unique_licenses_from_variables,
    get_unique_origins_from_indicators,
    get_unique_origins_from_variables,
    get_unique_sources_from_indicators,
    get_unique_sources_from_variables,
    is_nullable_series,
)

# Re-export License for backwards compatibility (some code imports it from variables)
from owid.catalog.core.meta import License

__all__ = [
    # New names (preferred)
    "Indicator",
    "IndicatorRolling",
    "UNNAMED_INDICATOR",
    "combine_indicators_metadata",
    "combine_indicators_display",
    "combine_indicators_presentation",
    "combine_indicators_processing_level",
    "combine_indicators_processing_logs",
    "combine_indicators_sort",
    "get_unique_sources_from_indicators",
    "get_unique_origins_from_indicators",
    "get_unique_licenses_from_indicators",
    "get_unique_description_key_points_from_indicators",
    # Backwards-compatible aliases
    "Variable",
    "VariableRolling",
    "UNNAMED_VARIABLE",
    "combine_variables_metadata",
    "combine_variables_display",
    "combine_variables_presentation",
    "combine_variables_processing_level",
    "combine_variables_processing_logs",
    "combine_variables_sort",
    "get_unique_sources_from_variables",
    "get_unique_origins_from_variables",
    "get_unique_licenses_from_variables",
    "get_unique_description_key_points_from_variables",
    # Common exports
    "METADATA_FIELDS",
    "OPERATION",
    "copy_metadata",
    "is_nullable_series",
    "License",
]
