title:
  title: "Electricity mix"
  title_variant: ""
default_selection:
  - "World"
default_dimensions:
  source: "total"
  metric: "generation"
topic_tags:
  - "Energy"
dimensions:
  - slug: "source"
    name: "Source"
    choices:
      - slug: "total"
        name: "Total"
      - slug: "coal"
        name: "Coal"
      - slug: "oil"
        name: "Oil"
      - slug: "gas"
        name: "Gas"
      - slug: "fossil"
        name: "Fossil fuels"
      - slug: "nuclear"
        name: "Nuclear"
      - slug: "hydro"
        name: "Hydropower"
      - slug: "wind"
        name: "Wind"
      - slug: "solar"
        name: "Solar"
      - slug: "solar_and_wind"
        name: "Solar and wind"
      - slug: "renewables"
        name: "Renewables"
      - slug: "other_renewables"
        name: "Other renewables"
      - slug: "bioenergy"
        name: "Bioenergy"
      - slug: "low_carbon"
        name: "Low-carbon"
  - slug: "metric"
    name: "Metric"
    choices:
      - slug: "generation"
        name: "Generation"
        description: "Electricity generation, in terawatt-hours"
      - slug: "per_capita"
        name: "Per capita"
        description: "Electricity generation per person, in kilowatt-hours"
      - slug: "share_of_generation"
        name: "Share of generation"
        description: "Share of total electricity generation"
      - slug: "demand"
        name: "Demand"
        description: "Total electricity demand, in terawatt-hours"
      - slug: "demand_per_capita"
        name: "Demand per capita"
        description: "Electricity demand per person, in kilowatt-hours"
      - slug: "net_imports"
        name: "Net imports"
        description: "Net electricity imports, in terawatt-hours"
      - slug: "imports_share"
        name: "Net imports as a share of demand"
        description: "Net electricity imports as a share of demand"
      - slug: "carbon_intensity"
        name: "Carbon intensity"
        description: "Carbon intensity of electricity, in grams of CO2 per kilowatt-hour"
views:
  # Views are generated programmatically in the step.
  []
