title:
  title: "Energy prices"
  titleVariant: "by energy source"
defaultSelection:
  - "European Union (27)"
topicTags:
  - "Energy"
dimensions:
  - slug: "frequency"
    name: "Frequency"
    choices:
      - slug: "annual"
        name: "Annual"
        description: "Annual data"
      - slug: "monthly"
        name: "Monthly"
        description: "Monthly data"
  - slug: "source"
    name: "Energy source"
    choices:
      - slug: "electricity"
        name: "Electricity"
      - slug: "gas"
        name: "Gas"
  - slug: "price_component"
    name: "Price type"
    choices:
      - slug: "total_price_including_taxes"
        name: "Consumer price"
        description: "Consumer price including all taxes and levies"
        group: Total price
      - slug: "wholesale"
        name: "Wholesale price"
        description: "Wholesale price"
        group: Total price
      - slug: "consumer_price_components"
        name: "Consumer price components"
        description: "Consumer price separated in its individual components"
        group: Price components disaggregated
  - slug: "consumer"
    name: "Consumer type"
    choices:
      - slug: "household"
        name: "Households"
        description: "Household consumers"
      - slug: "non_household"
        name: "Non-households"
        description: "Non-household consumers"
      - slug: "all"
        name: "All consumers"
        description: "All consumers"
  - slug: "unit"
    name: "Unit"
    choices:
      - slug: "euro"
        name: "Euro"
        description: "Price in euros"
      - slug: "pps"
        name: "PPS"
        description: "Price in Purchasing Power Standard"
views:
  # Views will be filled out programmatically.
  []
