title:
  title: Energy use
  titleVariant: by energy source
defaultSelection:
  - World
topicTags:
  - Energy
dimensions:
  - slug: source
    name: Energy source
    choices:
      - slug: overview
        name: Overview
        group: Overview
      - slug: all
        name: All sources
        group: Aggregates
        description: Total energy use
      - slug: fossil
        name: Fossil fuels
        group: Aggregates
        description: The sum of coal, oil and gas
      - slug: coal
        name: Coal
        group: Fossil fuels
      - slug: oil
        name: Oil
        group: Fossil fuels
      - slug: gas
        name: Gas
        group: Fossil fuels
      - slug: low-carbon
        name: Low-carbon
        group: Aggregates
        description: The sum of nuclear and renewable sources
      - slug: nuclear
        name: Nuclear
        group: Low-carbon & renewables
      - slug: renewable
        name: Renewables (all)
        group: Aggregates
        description: Includes energy from hydropower, solar, wind, geothermal, wave and tidal, and bioenergy.
      - slug: hydro
        name: Hydropower
        group: Low-carbon & renewables
      - slug: solar-wind
        name: Solar and wind
        group: Low-carbon & renewables
      - slug: solar
        name: Solar
        group: Low-carbon & renewables
      - slug: wind
        name: Wind
        group: Low-carbon & renewables
  - slug: metric
    name: Metric
    choices:
      - slug: total
        name: Total consumption
        description: The amount of energy consumed nationally per year
      - slug: per_capita
        name: Consumption per capita
        description: The average amount of energy each person consumes per year
      - slug: share_total
        name: Share of total
        description: The share of total energy consumption that this source contributes
      - slug: proportional_change
        name: Proportional change
        description: The percentage change from the previous year
      - slug: absolute_change
        name: Absolute change
        description: The absolute change from the previous year

views:
  - dimensions:
      source: overview
      metric: total
    indicators:
      y:
        - "energy_mix#coal__twh"
        - "energy_mix#oil__twh"
        - "energy_mix#gas__twh"
        - "energy_mix#nuclear__twh__equivalent"
        - "energy_mix#hydro__twh__equivalent"
        - "energy_mix#solar__twh__equivalent"
        - "energy_mix#wind__twh__equivalent"
    config:
      $schema: https://files.ourworldindata.org/schemas/grapher-schema.005.json
      chartTypes: ["StackedArea"]
      tab: chart
      title: Total consumed energy by source
      subtitle: "[Primary energy](#dod:primaryenergy) consumption is measured in [terawatt-hours](#dod:watt-hours), using the [substitution method](#dod:substitutionmethod)."
  - dimensions:
      source: overview
      metric: per_capita
    indicators:
      y:
        - "energy_mix#coal_per_capita__kwh"
        - "energy_mix#oil_per_capita__kwh"
        - "energy_mix#gas_per_capita__kwh"
        - "energy_mix#nuclear_per_capita__kwh__equivalent"
        - "energy_mix#hydro_per_capita__kwh__equivalent"
        - "energy_mix#solar_per_capita__kwh__equivalent"
        - "energy_mix#wind_per_capita__kwh__equivalent"
    config:
      $schema: https://files.ourworldindata.org/schemas/grapher-schema.005.json
      chartTypes: ["StackedArea"]
  - dimensions:
      source: all
      metric: total
    indicators:
      y: "primary_energy_consumption#primary_energy_consumption__twh"
    config:
      $schema: https://files.ourworldindata.org/schemas/grapher-schema.005.json
      yAxis:
        min: 0
  - dimensions:
      source: all
      metric: per_capita
    indicators:
      y: "primary_energy_consumption#primary_energy_consumption_per_capita__kwh"
    config:
      $schema: https://files.ourworldindata.org/schemas/grapher-schema.005.json
      yAxis:
        min: 0
  # this would be 100%
  # - dimensions:
  #       source: all
  #       metric: share_total
  - dimensions:
      source: all
      metric: proportional_change
    indicators:
      y: "primary_energy_consumption#annual_change_in_primary_energy_consumption__pct"
  - dimensions:
      source: all
      metric: absolute_change
    indicators:
      y: "primary_energy_consumption#annual_change_in_primary_energy_consumption__twh"

  # the rest is added programatically
