"""This script has been autogenerated.
    Download full data set from here: https://platform.who.int/mortality/themes/theme-details/topics/indicator-groups/indicator-group-details/MDB/violence
    Click on the download button and then select 'full dataset'. It doesn't matter what age groups or years you select it will download them all anyway.
"""

import pathlib

import click
import pandas as pd

from etl.snapshot import add_snapshot

CURRENT_DIR = pathlib.Path(__file__).parent
LOCAL_FILE = "WHOMortalityDatabase_Deaths_sex_age_a_country_area_year-Violence_22nd December 2022 14_53.csv"


@click.command()
@click.option(
    "--upload/--skip-upload",
    default=True,
    type=bool,
    help="Upload dataset to Snapshot",
)
def main(upload: bool) -> None:
    # Read in the raw data from local file
    raw = pd.read_csv(LOCAL_FILE, skiprows=6, index_col=False)

    # Add snapsot of data
    add_snapshot("homicide/2023-01-03/who_mort_db.csv", dataframe=raw, upload=upload)


if __name__ == "__main__":
    main()
