"""Create the WID population snapshot from the CSV generated by ``wid_population.do``.

``wid_population.do`` (in this directory) extracts WID's population counts (npopul, ages 992 and
999, unit i) from WID.world via Stata — a single fast API call, unlike the hours-long main WID
extraction — and writes one CSV file here.

To update:

1. Run ``wid_population.do`` in a local Stata installation (a few minutes):
       stata-se -b do wid_population.do
   It writes ``wid_population_992_999_i.csv`` into this directory (snapshots/wid/<version>/).
2. Create the snapshot:
       etls wid/<version>/wid_population
   (pass ``--path-to-file <folder>`` to read the CSV from somewhere other than this directory.)
3. Delete the leftover CSV and Stata log:
       rm snapshots/wid/<version>/wid_population_992_999_i.csv snapshots/wid/<version>/wid_population.log
"""

from pathlib import Path

from etl.helpers import PathFinder

paths = PathFinder(__file__)

# The CSV produced by `wid_population.do`.
SOURCE_CSV = "wid_population_992_999_i.csv"


def run(upload: bool = True, path_to_file: str | None = None) -> None:
    """Create the WID population snapshot.

    Args:
        upload: Whether to upload the snapshot to S3.
        path_to_file: Folder containing the input CSV. Defaults to this snapshot directory.
    """
    folder = Path(path_to_file) if path_to_file else paths.snapshot_dir

    source_path = folder / SOURCE_CSV
    if not source_path.exists():
        raise FileNotFoundError(
            f"Expected '{SOURCE_CSV}' in {folder} (generated by wid_population.do). "
            f"Run the Stata script first and make sure its CSV is present."
        )

    snap = paths.init_snapshot(filename="wid_population.csv")
    snap.create_snapshot(filename=source_path, upload=upload)
