definitions:
  common_views:
    - dimensions:
        indicator: population_density
      config:
        title: Population density
    - dimensions:
        indicator: death_rate
      config:
        title: Death rate
    - dimensions:
        indicator: median_age
      config:
        title: Median age
    - dimensions:
        indicator: net_migration
      config:
        title: Annual net migration
    - dimensions:
        indicator: net_migration_rate
      config:
        title: Annual net migration rate

# TODO: this is duplicated with config from un_wpp.manual.config.yml
config:
  explorerTitle: "Population & Demography"
  explorerSubtitle: "Explore data from the United Nations World Population Prospects."
  wpBlockId: 52216
  hasMapTab: true
  thumbnail: "https://owid.cloud/app/uploads/2022/07/Population-Data-Explorer.png"
  isPublished: true
  selection:
    - China
    - India
    - United States
    - Indonesia
    - Pakistan
    - Nigeria
    - Brazil
    - Japan
  pickerColumnSlugs:
    - location
    - population__all__all__records
    - population_change__all__all__records
    - population_density__all__all__records
    - births__all__all__records
    - birth_rate__all__all__records
    - deaths__all__all__records
    - death_rate__all__all__records
    - fertility_rate__all__all__records
    - growth_natural_rate__all__all__records
    - growth_rate__all__all__records
    - life_expectancy__all__at_birth__records
    - net_migration__all__all__records
    - net_migration_rate__all__all__records
    - sex_ratio__none__at_birth__records
    - dependency_ratio_total__all__none__records
    - dependency_ratio_child__all__none__records
    - dependency_ratio_old__all__none__records
    - median_age__all__all__records

dimensions:
  - slug: indicator
    name: indicator
    choices:
      - slug: population
        name: Population
      - slug: population_change
        name: Annual population change
      - slug: growth_rate
        name: Population growth rate
      - slug: natural_change_rate
        name: Natural population growth rate
      - slug: population_density
        name: Population density
      - slug: dependency_ratio
        name: Dependency ratio
      - slug: net_migration
        name: Net migration
      - slug: net_migration_rate
        name: Net migration rate
      - slug: deaths
        name: Deaths
      - slug: death_rate
        name: Death rate
      - slug: median_age
        name: Median age
      - slug: life_expectancy
        name: Life expectancy
      - slug: fertility_rate
        name: Fertility rate
      - slug: births
        name: Births
      - slug: birth_rate
        name: Birth rate

  - slug: sex
    name: Sex
    choices:
      - slug: all
        name: Both sexes
        description: null
      - slug: female
        name: Female
        description: null
      - slug: male
        name: Male
        description: null
    presentation:
      type: radio
  - slug: age
    name: Age
    choices:
      - slug: all
        name: Total
        description: null
      - slug: "0"
        name: Under 1 year
        description: null
      - slug: 0-4
        name: Under 5 years
        description: null
      - slug: 0-14
        name: Under 15 years
        description: null
      - slug: 0-24
        name: Under 25 years
        description: null
      - slug: "total"
        name: Total dependency ratio
        description: null
      - slug: "youth"
        name: Youth dependency ratio
        description: null
      - slug: "old"
        name: Old-age dependency ratio
        description: null

  - slug: variant
    name: Projection scenario
    choices:
      - slug: estimates
        name: None
        description: null
      - slug: low
        name: Low
        description: null
      - slug: medium
        name: Medium
        description: null
      - slug: high
        name: High
        description: null
    presentation:
      type: radio

views: []
