config:
  explorerTitle: "Population & Demography"
  explorerSubtitle: "Explore data from the United Nations World Population Prospects."
  wpBlockId: 52216
  hasMapTab: true
  thumbnail: "https://owid.cloud/app/uploads/2022/07/Population-Data-Explorer.png"
  isPublished: true

dimensions:
  - slug: indicator
    name: indicator
    choices:
      - slug: population
        name: Population
      - slug: population_change
        name: Annual population change
      - slug: population_density
        name: Population density
      - slug: dependency_ratio
        name: Dependency ratio
      - slug: net_migration
        name: Net migration
      - slug: net_migration_rate
        name: Net migration rate
      - slug: deaths
        name: Deaths
      - slug: death_rate
        name: Death rate

  - slug: sex
    name: Sex
    choices:
      - slug: all
        name: Both sexes
        description: null
      - slug: female
        name: Female
        description: null
      - slug: male
        name: Male
        description: null
    presentation:
      type: radio
  - slug: age
    name: Age
    choices:
      - slug: all
        name: Total
        description: null
      - slug: "0"
        name: Under 1 year
        description: null
      - slug: 0-4
        name: Under 5 years
        description: null
      - slug: 0-14
        name: Under 15 years
        description: null
      - slug: 0-24
        name: Under 25 years
        description: null
      - slug: "total"
        name: Total dependency ratio
        description: null
      - slug: "youth"
        name: Youth dependency ratio
        description: null
      - slug: "old"
        name: Old-age dependency ratio
        description: null

  - slug: variant
    name: Projection scenario
    choices:
      - slug: estimates
        name: None
        description: null
      - slug: low
        name: Low
        description: null
      - slug: medium
        name: Medium
        description: null
      - slug: high
        name: High
        description: null
    presentation:
      type: radio

views: []
