# Use this file to add new apps (or pages) to Wizard (see property 'sections')
#
# There are two main properties in this file:
# - etl: This is the section for the ETL apps. Each app in this section will be shown in the ETL home page.
# - sections: This is a list of sections. Each section is a group of apps. Each section will have its own home page.
#
# HOW TO ADD A NEW APP?
# ----------------------
# Each app should be added as an item in the 'apps' property of the section you want this app to live.
#
# Your app should have the following properties:
# - title (str): Title of the app. This will be shown in the home page and sidebar menu of Wizard.
# - alias (str): [NOT WORKING ATM] Alias of the app. This is used if you want to directly access the app from the command line (e.g. `etl-wizard [alias]`).
# - description (str): Description of the app. This will be shown in the card of the app in the home page of Wizard.
# - maintenaner (str): Slack handle of the person responsible for the app.
# - entrypoint (str): Path to the main file of the app. This file should be the streamlit python script.
# - emoji (str): Emoji to show in the sidebar menu.
# - enabled (bool): Whether the app is enabled or not. If it's not enabled, it won't be shown at all.
# - image_url (str): Link to the image you want to show on the card in the home page of Wizard.

etl:
  title: ETL steps
  description: Create an ETL step.
  steps:
    snapshot:
      title: "Snapshot"
      alias: snapshot
      entrypoint: etl_steps/snapshot.py
      emoji: "1️⃣"
      image_url: "https://cdn.pixabay.com/photo/2014/10/16/09/15/lens-490806_1280.jpg"
    meadow:
      title: "Meadow"
      alias: meadow
      entrypoint: etl_steps/meadow.py
      emoji: "2️⃣"
      image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Blumenwiese_bei_Obermaiselstein05.jpg/1024px-Blumenwiese_bei_Obermaiselstein05.jpg"
    garden:
      title: "Garden"
      alias: garden
      entrypoint: etl_steps/garden.py
      emoji: "3️⃣"
      image_url: "https://upload.wikimedia.org/wikipedia/commons/2/27/Butchart_gardens.JPG"
    grapher:
      title: "Grapher"
      alias: grapher
      entrypoint: etl_steps/grapher.py
      emoji: "4️⃣"
      image_url: "https://pbs.twimg.com/media/EbHwdjwUcAEfen4?format=jpg&name=large"
    fasttrack:
      title: "Fast Track"
      alias: fasttrack
      entrypoint: fasttrack/app.py
      emoji: "🏎️"
      image_url: "https://upload.wikimedia.org/wikipedia/commons/b/be/Alonso_%28Renault%29_qualifying_at_USGP_2005.jpg"

sections:
  - title: "Charts"
    description: |-
      Create chart revisions, and synchronize aproved revisions between servers.
    apps:
      - title: "Chart revision baker"
        alias: charts
        entrypoint: charts/__main__.py
        description: Prepare chart revisions.
        maintainer: "@lucas"
        emoji: "🧑‍🍳"
        image_url: "https://camo.githubusercontent.com/38a295d2c16cd880446f874a786e94fb168d6aadfdcbc4c8b7dd45c8337b6d1d/68747470733a2f2f6f7572776f726c64696e646174612e6f72672f677261706865722f6578706f7274732f6c6966652d657870656374616e63792e737667"
      - title: "Staging Sync"
        alias: staging_sync
        entrypoint: ../staging_sync/app.py
        description: Sync charts between servers.
        maintainer: "@mojmir"
        emoji: "🔄"
        image_url: "https://cdn.pixabay.com/photo/2018/04/12/18/13/sync-3314296_1280.png"

  - title: "Metadata"
    description: |-
      Tools to improve our metadata or learn how to use it.
    apps:
    - title: "MetaGPT"
      description: "Migrate old metadata to new format."
      maintainer: "@veronika / @lucas"
      entrypoint: metagpt.py
      emoji: "🤖"
      alias: metagpt
      image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/ChatGPT_logo.svg/1024px-ChatGPT_logo.svg.png"
    - title: "Metadata playground"
      alias: metaplay
      description: "Understand how metadata is presented in data pages."
      maintainer: "@lucas"
      entrypoint: metaplay.py
      emoji: "🏐"
      image_url: "https://upload.wikimedia.org/wikipedia/commons/d/d4/PlayEquipComboPlastic_wb.jpg"

  - title: "Others"
    description: |-
      Other helpful tools in the ETL ecosystem.
    apps:
      - title: "Dataset Explorer"
        alias: dataexp
        description: "Explore datasets and their metadata."
        maintainer: "@lucas"
        entrypoint: dataset_explorer.py
        emoji: "🔍"
        image_url: "https://upload.wikimedia.org/wikipedia/commons/c/c3/NGC_4414_%28NASA-med%29.jpg"
      - title: "Harmonizer"
        alias: harmonizer
        description: "Harmonize column of table."
        maintainer: "@lucas"
        entrypoint: harmonize.py
        emoji: "🎶"
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/C_triad.svg/2560px-C_triad.svg.png"

