# Use this file to add new apps (or pages) to Wizard (see property 'sections')
#
# There are three main properties in this file:
# - main: Reserved for 'Home' and 'Expert' pages.
# - etl: This is the section for the ETL apps. Each app in this section will be shown in the ETL home page.
# - sections: This is a list of sections. Each section is a group of apps. Each section will have its own home page.
#
# HOW TO ADD A NEW APP?
# ----------------------
# Each app should be added as an item in the 'apps' property of the section you want this app to live.
#
# Your app should have the following properties:
# - title (str): Title of the app. This will be shown in the home page and sidebar menu of Wizard.
# - alias (str): [not needed in etl.steps] Alias of the app. This is used if you want to directly access the app from the command line (e.g. `etlwiz [alias]`).
# - description (str): Description of the app. This will be shown in the card of the app in the home page of Wizard.
# - maintenaner (str): Slack handle of the person responsible for the app.
# - entrypoint (str): Path to the main file of the app. This file should be the streamlit python script.
# - icon (str): Emoji or material icon to show in the sidebar menu. Use from https://fonts.google.com/icons?icon.set=Material+Symbols&icon.style=Rounded
# - image_url (str): Link to the image you want to show on the card in the home page of Wizard.
# - disable (bool): Whether the app is disabled in certain settings. To detect if the app is running in a remote setting, it checks the value of the environment variable `ENV`.
#     bool: Whether the app is disabled in all settings.
#     dict: Whether the app is disabled in certain settings. The key is the setting and the value is a boolean. Available settings (keys) are 'production', 'staging', 'dev'. 'dev' stands for local environments.

# Main pages
main:
  home:
    title: "Home"
    description: "App homepage"
    maintainer: "@lucas"
    entrypoint: home.py
    icon: ":material/home:"
  expert:
    title: "Expert"
    description: "Ask the expert ETL questions!"
    maintainer:
      - "@lucas"
      - "@daniel"
    entrypoint: app_pages/expert/app.py
    icon: ":material/lightbulb_2:"
  analytics:
    title: "Analytics (external)"
    description: "Learn more about OWID in Data!"
    maintainer:
      - "@bobbie"
      - "@lucas"
    entrypoint: app_pages/analytics.py
    icon: ":material/bar_chart:"

# ETL steps
etl:
  title: ETL steps
  description: Create an ETL step.
  steps:
    snapshot:
      title: "Snapshot"
      entrypoint: etl_steps/snapshot.py
      icon: ":material/photo_camera:"
      image_url: "https://greatescapepublishing.com/wp-content/uploads/2019/11/30463274482_90aff8a230_c.jpg"
      disable:
        "production": True
    data:
      title: "Data step"
      entrypoint: etl_steps/data.py
      icon: ":material/table:"
      image_url: "https://upload.wikimedia.org/wikipedia/commons/b/b3/Indochinese_leopard.jpg"
      disable:
        "production": True
    fasttrack:
      title: "Fast Track"
      alias: fasttrack
      entrypoint: app_pages/fasttrack/app.py
      icon: ":material/fast_forward:"
      image_url: "https://upload.wikimedia.org/wikipedia/commons/b/be/Alonso_%28Renault%29_qualifying_at_USGP_2005.jpg"

sections:
  - title: "Data curation"
    description: |-
      Updates, data edits, etc.
    apps:
      - title: "Indicator Upgrader"
        alias: indicator-upgrade
        entrypoint: app_pages/indicator_upgrade/app.py
        description: Migrate indicators in charts
        maintainer: "@lucas"
        icon: ":material/upgrade:"
        image_url: "https://wallpapers.com/images/hd/pokemon-evolution-1920-x-1080-wallpaper-h5u6nbg98e3tibyn.jpg"
        disable:
          production: True
      - title: "Anomalist"
        alias: anomalist
        entrypoint: app_pages/anomalist/app.py
        description: List anomalies in data
        maintainer: "@lucas"
        icon: ":material/planner_review:"
        image_url: "https://www.shutterstock.com/image-illustration/multitude-endless-standing-white-eggs-260nw-310142192.jpg"
        disable:
          production: True
      - title: "Chart Diff"
        alias: chart-diff
        entrypoint: app_pages/chart_diff/app.py
        description: Compare charts in staging and prod
        maintainer: "@mojmir"
        icon: ":material/difference:"
        image_url: "https://images.squarespace-cdn.com/content/v1/5ea8287254c2e00f35d1cc48/1595511684480-6RM6YK3XZGB2SD21GPGP/20140620appletoapplescomparison.jpg"
        disable:
          production: True
      - title: "Harmonizer"
        alias: harmonizer
        description: "Harmonize a column of a table"
        maintainer: "@lucas"
        entrypoint: app_pages/harmonizer.py
        icon: ":material/music_note:"
        image_url: "https://www.shutterstock.com/image-vector/abstract-vector-musical-background-music-260nw-485443810.jpg"

  - title: "Data monitoring"
    description: |-
      Control panel for ETL steps.
    apps:
      - title: "Dashboard"
        alias: dashboard
        entrypoint: app_pages/dashboard.py
        description: Control panel for ETL steps
        maintainer: "@pablo"
        icon: ":material/tv_gen:"
        image_url: "https://cdn.pixabay.com/photo/2018/09/04/17/02/indicator-3654257_960_720.jpg"
      - title: "Datasets"
        alias: dataexp
        description: "Explore datasets and their metadata"
        maintainer: "@lucas"
        entrypoint: app_pages/dataset_explorer.py
        icon: ":material/search:"
        image_url: "https://upload.wikimedia.org/wikipedia/commons/c/c3/NGC_4414_%28NASA-med%29.jpg"
      - title: "Producer analytics"
        alias: producer-analytics
        description: "Extract analytics to share with data producers"
        maintainer: "@pablo"
        entrypoint: app_pages/producer_analytics.py
        icon: ":material/analytics:"
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Wikimedia_Product_Analytics_team_logo.svg/512px-Wikimedia_Product_Analytics_team_logo.svg.png"

  - title: "Explorers"
    description: |-
      Explorer tools.
    apps:
      - title: "Map Bracketer"
        alias: map_brackets
        entrypoint: app_pages/map_brackets.py
        description: Create optimal map brackets
        maintainer: "@pablo"
        icon: ":material/map:"
        image_url: "https://upload.wikimedia.org/wikipedia/en/8/8c/Human_Language_Families_Map_%28Wikipedia_Colors_.PNG"
      - title: "ID to Path"
        alias: explorer_editor
        entrypoint: app_pages/explorer_edit.py
        description: Migrate id-based explorers
        maintainer: "@lucas"
        icon: ":material/explore:"
        image_url: "https://upload.wikimedia.org/wikipedia/en/1/18/Dora_the_Explorer_2004_album_cover.jpg"

  - title: "Research"
    description: |-
      Research tools.
    apps:
      - title: "Insight search"
        alias: insight_search
        description: "Browse data insights by their semantic similarity"
        maintainer: "@pablo"
        entrypoint: app_pages/insight_search.py
        icon: ":material/search:"
        image_url: "https://img.freepik.com/premium-photo/librarian-cataloging-new-books-library-database_1237301-1719.jpg"
      - title: "Insighter"
        alias: insighter
        description: "Data insights with GPT"
        maintainer: "@daniel"
        entrypoint: app_pages/datainsight_robot.py
        icon: ":material/stylus_note:"
        image_url: "https://cdn.cpdonline.co.uk/wp-content/uploads/2023/08/03153310/Starting-To-Become-A-Writer-1200x350.jpg"

  - title: "Misc"
    description: |-
      Other helpful tools in the ETL ecosystem.
    apps:
      - title: "News"
        alias: news
        description: "Latest ETL news"
        maintainer: "@lucas"
        entrypoint: app_pages/news.py
        icon: ":material/newspaper:"
        image_url: "https://img.freepik.com/free-photo/top-view-old-french-newspaper-pieces_23-2149318857.jpg"
      - title: "owidle"
        alias: owidle
        description: "Guess the country game!"
        maintainer: "@lucas"
        entrypoint: app_pages/owidle.py
        icon: ":material/videogame_asset:"
        image_url: "https://t3.ftcdn.net/jpg/06/26/23/36/360_F_626233679_tesiSRP9Jinq5wS0ZgbdJ6k5adupmgKl.jpg"
      - title: "Chart animation"
        alias: chart-animation
        description: "Create an animated GIF or a video from a chart"
        maintainer: "@pablo"
        entrypoint: app_pages/chart_animation.py
        icon: ":material/animated_images:"
        image_url: "https://img.freepik.com/free-photo/abstract-yellow-smooth-wave-lines_1017-24863.jpg"

  - title: "Metadata"
    description: |-
      Improve our metadata or learn how to use it.
    apps:
      - title: "Meta Upgrader"
        description: "Migrate old metadata to new format."
        maintainer: "@veronika / @lucas"
        entrypoint: app_pages/metagpt.py
        icon: ":material/upgrade:"
        alias: metagpt
        image_url: "https://cdn.pixabay.com/photo/2016/12/04/18/58/instagram-1882329_1280.png"
        disable:
          "production": True
          "staging": True
      - title: "Meta Playground"
        alias: metaplay
        description: "How is metadata presented in data pages?"
        maintainer: "@lucas"
        entrypoint: app_pages/metaplay.py
        icon: ":material/sports_volleyball:"
        image_url: "https://upload.wikimedia.org/wikipedia/commons/d/d4/PlayEquipComboPlastic_wb.jpg"
        disable:
          "production": True
          "staging": True

  - title: "ETL Steps (legacy)"
    description: "Keeping this temporary"
    apps:
      - alias: express
        title: "Express"
        description: "Add all data steps."
        entrypoint: etl_steps/express.py
        icon: ":material/bolt:"
        image_url: "https://upload.wikimedia.org/wikipedia/commons/b/b3/Indochinese_leopard.jpg"
        disable:
          "production": True
      - alias: meadow
        title: "Meadow"
        description: "Add meadow step."
        entrypoint: etl_steps/meadow.py
        icon: ":material/nature:"
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Blumenwiese_bei_Obermaiselstein05.jpg/1024px-Blumenwiese_bei_Obermaiselstein05.jpg"
        disable:
          "production": True
      - alias: garden
        title: "Garden"
        description: "Add garden step."
        entrypoint: etl_steps/garden.py
        icon: ":material/deceased:"
        image_url: "https://upload.wikimedia.org/wikipedia/commons/2/27/Butchart_gardens.JPG"
        disable:
          "production": True
      - alias: grapher
        title: "Grapher"
        description: "Add grapher step."
        entrypoint: etl_steps/grapher.py
        icon: ":material/database:"
        image_url: "https://pbs.twimg.com/media/EbHwdjwUcAEfen4?format=jpg&name=large"
        disable:
          "production": True
# legacy:
#   description: |-
#     The pages below are legacy now. They are kept in case the new pages are not working properly.
#   apps:
#     - title:
#       alias:
#       entrypoint:
#       description:
#       maintainer:
#       icon:
#       image_url:
