chart_config_id: 01a11b1e-18fc-713b-a866-5ec76fb26bae
grapher_schema: "011"
topic_tags:
  - "Foreign Aid"
  - "Climate Change"
dimensions: []
views:
  - dimensions: {}
    indicators:
      y:
        - catalogPath: "climate_related_oda_by_donor#climate_related_share_of_bilateral_total"
    config:
      title: "Share of all bilateral aid given that is climate-related"
      subtitle: "Bilateral aid that targets climate change mitigation, adaptation, or both, as a share of all bilateral aid given by each donor."
      note: "Based on commitments. All bilateral aid includes aid that the OECD's climate markers don't apply to, such as general budget support and the costs of hosting refugees in donor countries, but not contributions to multilateral organizations. Projects that target climate as a secondary objective are counted at their full value. DAC members are the members of the OECD Development Assistance Committee."
      tab: "chart"
      hasMapTab: true
      chartTypes:
        - "LineChart"
      minTime: 2010
      yAxis:
        min: 0
        facetDomain: shared
      selectedFacetStrategy: entity
      selectedEntityNames:
        - "South Korea"
        - "United Kingdom"
        - "France"
        - "Germany"
        - "DAC members"
        - "United States"
        - "Japan"
        - "Netherlands"
        - "Canada"
