title:
  title: Data on conflict since 1946
  title_variant: "from UCDP/PRIO"
default_selection:
  - World

default_dimensions:
  indicator: deaths
  conflict_type: state_based_stacked
  estimate: best

dimensions:
  - slug: indicator
    name: Measure
    choices:
      - slug: "deaths"
        name: "Deaths"
        group: How deadly are conflicts?
      - slug: "death_rate"
        name: "Death rate"
        description: The number of deaths divided by the total population
        group: How deadly are conflicts?
      - slug: "wars_ongoing"
        name: "Number of conflicts"
        group: How common are conflicts?
      - slug: "wars_ongoing_country_rate"
        name: "Conflict rate"
        description: The number of conflicts divided by the number of countries
        group: How common are conflicts?
  - slug: conflict_type
    name: "Conflict type"
    choices:
      - slug: "state-based"
        name: "All involving states"
        # description: All conflicts involving states
      - slug: "state_based_stacked"
        name: "All involving states (by type)"
        description: Breakdown by conflict type
      - slug: "interstate"
        name: "Interstate conflicts"
        description: Between states
      - slug: "intrastate (internationalized)"
        name: "Foreign-backed civil conflicts"
        description: Between a state and another armed group, involving a foreign state
      - slug: "intrastate (non-internationalized)"
        name: "Domestic civil conflicts"
        description: Between a state and another armed group, not involving a foreign state
      - slug: "extrasystemic"
        name: "Colonial conflicts"
        description: Between a state and another armed group outside its territory
  - slug: estimate
    name: "Estimate"
    choices:
      - slug: best
        name: Best estimate only
      - slug: best_ci
        name: Show high and low estimates
      - slug: low
        name: Low estimate
      - slug: high
        name: High estimate
      - slug: na
        name: "Not applicable"
        description: "Not applicable"
      - slug: low_high
        name: "Low and high estimates"

views: []
