title:
  title: Data on conflict since 1946
  title_variant: "from UCDP/PRIO"
default_selection:
  - World

dimensions:
  - slug: indicator
    name: Measure
    choices:
      - slug: "deaths"
        name: "Deaths"
        # description: People moving away from country
      - slug: "death_rate"
        name: "Death rate"
        description: The number of deaths divided by the total population
  - slug: conflict_type
    name: "Conflict type"
    choices:
      - slug: "state-based"
        name: "All"
        description: All conflicts involving states
      - slug: "state-based-stacked"
        name: "All (breakdown)"
        description: Breakdown by conflict type
      - slug: "interstate"
        name: "Interstate conflicts"
        description: Between states
      - slug: "intrastate (internationalized)"
        name: "Foreign-backed civil conflicts"
        description: Between a state and another armed group, involving a foreign state
      - slug: "intrastate (non-internationalized)"
        name: "Domestic civil conflicts"
        description: Between a state and another armed group, not involving a foreign state
      - slug: "extrasystemic"
        name: "Colonial conflicts"
        description: Between a state and another armed group outside its territory
  - slug: estimate
    name: "Estimate"
    choices:
      - slug: best
        name: Best estimate
      - slug: best-ci
        name: Best estimate (with CI)
      - slug: low
        name: Low estimate
      - slug: high
        name: High estimate
      - slug: na
        name: "-"
      - slug: low_high
        name: "Low and high estimates"

views: []
