title:
  title: Data on conflict since 1989
  title_variant: "from UCDP"
default_selection:
  - World

dimensions:
  - slug: indicator
    name: Measure
    choices:
      - slug: "deaths"
        name: "Deaths"
      - slug: "death_rate"
        name: "Death rate"
        description: The number of deaths divided by the total population
      - slug: "num_conflicts"
        name: "Number of conflicts"

  - slug: conflict_type
    name: "Conflict type"
    choices:
      - slug: "all"
        name: "All armed conflicts"
      - slug: all_stacked
        name: "All armed conflicts (breakdown)"
        description: Breakdown by conflict type
      - slug: "intrastate"
        name: "Interstate conflicts"
        description: Between states
      - slug: "interstate"
        name: "Civil conflicts"
        description: Between a state and another armed group
      - slug: "non-state conflict"
        name: "Non-state conflicts"
        description: Between non-state armed groups
      - slug: "one-sided violence"
        name: "Violence against civilians"

  - slug: people
    name: "Deaths"
    choices:
      - slug: "all"
        name: "All deaths"
        description: All deaths in armed conflicts
      - slug: "all_stacked"
        name: "All deaths (breakdown)"
        description: Breakdown by death type
      - slug: na
        name: "Not applicable"

  - slug: estimate
    name: "Estimate"
    choices:
      - slug: "best"
        name: "Best estimate"
      - slug: best_ci
        name: Best estimate (with CI)
      - slug: "high"
        name: "High estimate"
      - slug: "low"
        name: "Low estimate"
      - slug: na
        name: "Not applicable"

views: []
