"""Create the five WID snapshots from the CSV files generated by ``wid_indices.do``.

A single script handles all five snapshots: ``wid_indices.do`` (in this directory) extracts the
data from WID.world via Stata and writes five CSV files here, so instead of one near-identical
script per file we map each of those CSVs to its snapshot and create them all in one go.

To update:

1. Open ``wid_indices.do`` in a local Stata installation and run it (it takes several hours).
   It writes the five CSV files listed in ``FILES`` into this directory (snapshots/wid/<version>/).
2. Create all five snapshots with a single command:
       etls wid/<version>/world_inequality_database
   (pass ``--path-to-file <folder>`` to read the CSVs from somewhere other than this directory.)
3. Delete the leftover csv files:
       rm snapshots/wid/<version>/*.csv
"""

from pathlib import Path

from etl.helpers import PathFinder

paths = PathFinder(__file__)

# Map each snapshot (the `.dvc` next to this script) to the CSV produced by `wid_indices.do`.
FILES = {
    "world_inequality_database.csv": "wid_indices_992j_exclude.csv",
    "world_inequality_database_with_extrapolations.csv": "wid_indices_992j_include.csv",
    "world_inequality_database_distribution.csv": "wid_distribution_992j_exclude.csv",
    "world_inequality_database_distribution_with_extrapolations.csv": "wid_distribution_992j_include.csv",
    "world_inequality_database_fiscal.csv": "wid_indices_fiscal_992ijt_exclude.csv",
}


def run(upload: bool = True, path_to_file: str | None = None) -> None:
    """Create the WID snapshots.

    Args:
        upload: Whether to upload the snapshots to S3.
        path_to_file: Folder containing the five input CSVs. Defaults to this snapshot directory.
    """
    folder = Path(path_to_file) if path_to_file else paths.snapshot_dir

    for snapshot_file, source_csv in FILES.items():
        source_path = folder / source_csv
        if not source_path.exists():
            raise FileNotFoundError(
                f"Expected '{source_csv}' in {folder} (generated by wid_indices.do). "
                f"Run the Stata script first and make sure its CSVs are present."
            )

        snap = paths.init_snapshot(filename=snapshot_file)
        snap.create_snapshot(filename=source_path, upload=upload)
