"""Create the WID aggregate wealth snapshot from the CSV file generated by ``wid_indices.do``.

This is the balance sheet of the households and NPISH sector combined (net wealth, debt, housing
and land, business assets and financial assets), as a ratio to net national income.

It has its own script instead of joining ``world_inequality_database.py`` because that one refuses
to run unless all five of its CSV files are present, while this snapshot can be rebuilt on its own
in a few minutes (``global aggregate_wealth_only 1`` in ``wid_indices.do``).

To update:

1. Open ``wid_indices.do`` in a local Stata installation and run it. It writes
   ``wid_aggregate_wealth.csv`` into this directory (snapshots/wid/<version>/).
2. Create the snapshot:
       etls wid/<version>/world_inequality_database_aggregate_wealth
   (pass ``--path-to-file <folder>`` to read the CSV from somewhere other than this directory.)
3. Delete the leftover csv file:
       rm snapshots/wid/<version>/wid_aggregate_wealth.csv
"""

from pathlib import Path

from etl.helpers import PathFinder

paths = PathFinder(__file__)

# CSV file produced by `wid_indices.do`.
SOURCE_CSV = "wid_aggregate_wealth.csv"


def run(upload: bool = True, path_to_file: str | None = None) -> None:
    """Create the WID aggregate wealth snapshot.

    Args:
        upload: Whether to upload the snapshot to S3.
        path_to_file: Folder containing the input CSV. Defaults to this snapshot directory.
    """
    folder = Path(path_to_file) if path_to_file else paths.snapshot_dir
    source_path = folder / SOURCE_CSV

    if not source_path.exists():
        raise FileNotFoundError(
            f"Expected '{SOURCE_CSV}' in {folder} (generated by wid_indices.do). "
            f"Run the Stata script first and make sure its CSV is present."
        )

    snap = paths.init_snapshot()
    snap.create_snapshot(filename=source_path, upload=upload)
