title:
  title: Trade in goods
  title_variant: by partner country

default_selection:
  - China
  - United States
  - Japan
  - Germany
  - Peru

dimensions:
  - name: Country
    slug: counterpart_country
  - name: Metric
    slug: metric
    choices:
      - slug: "exports_of_goods__free_on_board__fob__share"
        name: "Exports of goods (Free on Board)"
        description: Share of total exports of goods (Free on Board)
      - slug: "imports_of_goods__cost_insurance_freight__cif__share"
        name: "Imports of goods (Cost, Insurance, Freight)"
        description: Share of total imports of goods (Cost, Insurance, Freight)
      - slug: "trade_balance_goods__share"
        name: "Trade balance of goods"
        description: Net trade in goods as share of total trade volume
      - slug: "share_of_total_trade"
        name: "Share of total trade"
        description: Share of total trade volume (exports plus imports)

views: []
