definitions:
  config: &config
    tab: map
    originUrl: ourworldindata.org/coronavirus
    hideAnnotationFieldsInTitle:
      entity: true
      time: true
      changeInPrefix: true
    $schema: https://files.ourworldindata.org/schemas/grapher-schema.006.json

title:
  title: COVID-19 confirmed cases
  titleVariant: ""
defaultSelection:
  - World
  - Europe
  - Asia
topicTags:
  - COVID-19

dimensions:
  - slug: period
    name: Period
    choices:
      - slug: weekly
        name: Weekly
        description: null
      - slug: biweekly
        name: Biweekly
        description: null

  - slug: metric
    name: Metric
    choices:
      - slug: absolute
        name: Absolute
        description: null
      - slug: per_capita
        name: Per million people
        description: null
      - slug: change
        name: Change from previous period
        description: null

views:
  - dimensions:
      period: weekly
      metric: absolute
    indicators:
      y: "cases_deaths#weekly_cases"
    config: *config
  - dimensions:
      period: weekly
      metric: per_capita
    indicators:
      y: "cases_deaths#weekly_cases_per_million"
    config: *config
  - dimensions:
      period: weekly
      metric: change
    indicators:
      y: "cases_deaths#weekly_pct_growth_cases"
    config: *config

  - dimensions:
      period: biweekly
      metric: absolute
    indicators:
      y: "cases_deaths#biweekly_cases"
    config: *config
  - dimensions:
      period: biweekly
      metric: per_capita
    indicators:
      y: "cases_deaths#biweekly_cases_per_million"
    config: *config
  - dimensions:
      period: biweekly
      metric: change
    indicators:
      y: "cases_deaths#biweekly_pct_growth_cases"
    config: *config
