definitions:
  common_views:
    - config:
        chartTypes: ["ScatterPlot"]
        minTime: "latest"
        note: ""
        subtitle: 7-day rolling average. Comparisons across countries are affected by
          differences in testing policies and reporting methods.
        # No details in title
        hideAnnotationFieldsInTitle:
          entity: true
          time: true
          changeInPrefix: true
        # Log
        yAxis:
          scaleType: log
          canChangeScaleType: true
          min: 0
        xAxis:
          scaleType: log
          canChangeScaleType: true
        comparisonLines:
          - label: Positive rate = 100%
            yEquals: x
          - label: 50%
            yEquals: 2*x
          - label: 20%
            yEquals: 5*x
          - label: 10%
            yEquals: 10*x
          - label: 5%
            yEquals: 20*x
          - label: 2%
            yEquals: 50*x
          - label: 1%
            yEquals: 100*x
          - label: 0.5%
            yEquals: 200*x
          - label: 0.2%
            yEquals: 500*x
          - label: 0.1%
            yEquals: 1000*x
          - label: 0.02%
            yEquals: 5000*x
        # Related Q
        relatedQuestions:
          - url: https://ourworldindata.org/covid-testing-data-archived
            text: Data on tests is no longer updated since June 2022
        # Origin URL
        originUrl: ourworldindata.org/coronavirus

title:
  title: "COVID-19: Tests and confirmed cases"
  title_variant: "Number of daily tests vs. daily new confirmed cases"
default_selection: []
topic_tags:
  - COVID-19

dimensions:
  - slug: normalize
    name: Normalization
    choices:
      - slug: absolute
        name: Absolute numbers
        description: null
      - slug: per_capita
        name: Per million people
        description: "Normalized by million people living in the country or region"

views:
  - dimensions:
      normalize: absolute
    indicators:
      y:
        catalogPath: testing#new_tests_7day_smoothed
        display:
          name: Daily tests
      x:
        catalogPath: cases_deaths#new_cases_7_day_avg_right
        display:
          name: Daily new confirmed cases due to COVID-19
      color: regions#owid_region
    config:
      title: "COVID-19: Daily tests vs. daily new confirmed cases"

  - dimensions:
      normalize: per_capita
    indicators:
      y:
        catalogPath: testing#new_tests_per_thousand_7day_smoothed
        display:
          conversionFactor: 1000
          name: Daily tests per million
      x:
        catalogPath: cases_deaths#new_cases_per_million_7_day_avg_right
        display:
          name: Daily confirmed cases per million people
      color: regions#owid_region
    config:
      title: "COVID-19: Daily tests vs. daily new confirmed cases per million people"
      selectedEntityNames: []
      excludedEntityNames:
        - Armenia
        - Peru
        - Ecuador
