definitions:
  table: grapher/covid/latest/google_mobility/google_mobility

title:
  title: Mobility during COVID-19 pandemic
  titleVariant: by place
defaultSelection:
  - United Kingdom
topicTags:
  - COVID-19

dimensions:
  - slug: place
    name: Place
    choices:
      - slug: all
        name: All places
        description: "See all places"
      - slug: Grocery and pharmacy
        name: Grocery and pharmacy
        description: null
      - slug: Parks
        name: Parks
        description: null
      - slug: Residential
        name: Residential
        description: null
      - slug: Retail and recreation
        name: Retail and recreation
        description: null
      - slug: Transit stations
        name: Transit stations
        description: null
      - slug: Workplaces
        name: Workplaces
        description: null

views:
  - dimensions:
      place: all
    indicators:
      y:
        - "{definitions.table}#trend__place_grocery_and_pharmacy"
        - "{definitions.table}#trend__place_parks"
        - "{definitions.table}#trend__place_residential"
        - "{definitions.table}#trend__place_retail_and_recreation"
        - "{definitions.table}#trend__place_workplaces"

    config:
      $schema: https://files.ourworldindata.org/schemas/grapher-schema.006.json
      title: "How did the number of visitors change since the beginning of the pandemic?"
      subtitle: This data shows how community movement in specific locations has changed relative to the period before the pandemic.
      note: It's not recommended to compare levels across countries; local differences in categories could be misleading.
      originUrl: ourworldindata.org/coronavirus
#   - dimensions:
#       type: hospital
#       metric: patients_per_capita
#     indicators:
#       y: "{definitions.table}#daily_occupancy_hosp_per_1m"
#   - dimensions:
#       type: hospital
#       metric: admissions
#     indicators:
#       y: "{definitions.table}#weekly_admissions_hosp"
#   - dimensions:
#       type: hospital
#       metric: admissions_per_capita
#     indicators:
#       y: "{definitions.table}#weekly_admissions_hosp_per_1m"

#   - dimensions:
#       type: icu
#       metric: patients
#     indicators:
#       y: "{definitions.table}#daily_occupancy_icu"
#   - dimensions:
#       type: icu
#       metric: patients_per_capita
#     indicators:
#       y: "{definitions.table}#daily_occupancy_icu_per_1m"
#   - dimensions:
#       type: icu
#       metric: admissions
#     indicators:
#       y: "{definitions.table}#weekly_admissions_icu"
#   - dimensions:
#       type: icu
#       metric: admissions_per_capita
#     indicators:
#       y: "{definitions.table}#weekly_admissions_icu_per_1m"
