definitions:
  table: grapher/covid/latest/vaccinations_manufacturer/vaccinations_manufacturer

title:
  title: COVID-19 vaccines
  titleVariant: "breakdowns"
defaultSelection:
  - High-income countries
  - Upper-middle-income countries
  - Lower-middle-income countries
  - Low-income countries
topicTags:
  - COVID-19

dimensions:
  - slug: breakdown
    name: Breakdown
    choices:
      - slug: manufacturer
        name: Manufacturer
        description: null
      - slug: income_group
        name: Income group
        description: null

views:
  - dimensions:
      breakdown: income_group
    indicators:
      y: "grapher/covid/latest/vaccinations_global/vaccinations_global#total_vaccinations_per_hundred"
    config:
      title: Test
      selectedEntityNames:
        - High-income countries
        - Upper-middle-countriesincome countries
        - Lower-middle-income countries
        - Low-income
  - dimensions:
      breakdown: manufacturer
    indicators:
      y:
        - "{definitions.table}#total_vaccinations__vaccine_pfizer_biontech"
        - "{definitions.table}#total_vaccinations__vaccine_moderna"
        - "{definitions.table}#total_vaccinations__vaccine_oxford_astrazeneca"
        - "{definitions.table}#total_vaccinations__vaccine_johnson_and_johnson"
        - "{definitions.table}#total_vaccinations__vaccine_sputnik_v"
        - "{definitions.table}#total_vaccinations__vaccine_sinovac"
        - "{definitions.table}#total_vaccinations__vaccine_sinopharm_beijing"
        - "{definitions.table}#total_vaccinations__vaccine_cansino"
        - "{definitions.table}#total_vaccinations__vaccine_novavax"
        - "{definitions.table}#total_vaccinations__vaccine_covaxin"
        - "{definitions.table}#total_vaccinations__vaccine_medicago"
        - "{definitions.table}#total_vaccinations__vaccine_sanofi_gsk"
        - "{definitions.table}#total_vaccinations__vaccine_skycovione"
        - "{definitions.table}#total_vaccinations__vaccine_valneva"
    config:
      type: "StackedArea"
      selectedEntityNames:
        - European Union (27)

