title:
  title: "COVID-19: Daily tests vs. daily new confirmed cases"
  titleVariant: ""
defaultSelection: []
topicTags:
  - COVID-19

dimensions:
  - slug: normalize
    name: Normalization
    choices:
      - slug: absolute
        name: None
        description: null
      - slug: per_capita
        name: Per million people
        description: null

views:
  - dimensions:
      normalize: absolute
    indicators:
      y: grapher/covid/latest/testing/testing#new_tests_7day_smoothed
      x: grapher/covid/latest/cases_deaths/cases_deaths#new_cases_7_day_avg_right
    config:
      chartTypes: ["ScatterPlot"]
      $schema: https://files.ourworldindata.org/schemas/grapher-schema.006.json
  - dimensions:
      normalize: per_capita
    indicators:
      y: grapher/covid/latest/testing/testing#new_tests_per_thousand_7day_smoothed
      x: grapher/covid/latest/cases_deaths/cases_deaths#new_cases_per_million_7_day_avg_right
      color: 123
    config:
      $schema: https://files.ourworldindata.org/schemas/grapher-schema.006.json
      chartTypes: ["ScatterPlot"]
      map:
        colorScale:
          binningStrategy: equalInterval
      maxTime: 884
      yAxis:
        scaleType: log
        canChangeScaleType: true
        min: 0
      colorScale:
        binningStrategy: equalInterval
      minTime: 884
      hideAnnotationFieldsInTitle:
        entity: true
        time: true
        changeInPrefix: true
      xAxis:
        scaleType: log
        canChangeScaleType: true
      slug: covid-19-daily-tests-vs-daily-new-confirmed-cases-per-million
      title: "COVID-19: Daily tests vs. daily new confirmed cases per million"
      subtitle: 7-day rolling average. Comparisons across countries are affected by
        differences in testing policies and reporting methods.
      note: Our data on COVID-19 tests and positive rate is no longer updated since 23
        June 2022.
      originUrl: ourworldindata.org/coronavirus
      selectedEntityNames: []
      excludedEntities:
        - 97
        - 201
        - 21
      comparisonLines:
        - label: Positive rate = 100%
          yEquals: x
        - label: 50%
          yEquals: 2*x
        - label: 20%
          yEquals: 5*x
        - label: 10%
          yEquals: 10*x
        - label: 5%
          yEquals: 20*x
        - label: 2%
          yEquals: 50*x
        - label: 1%
          yEquals: 100*x
        - label: 0.5%
          yEquals: 200*x
        - label: 0.2%
          yEquals: 500*x
        - label: 0.1%
          yEquals: 1000*x
        - label: 0.02%
          yEquals: 5000*x
      relatedQuestions:
        - url: https://ourworldindata.org/covid-testing-data-archived
          text: Data on tests is no longer updated since June 2022
