definitions:
  common_views:
    - config: &config_base
        subtitle: "This data shows how community movement in specific locations has changed relative to the period before the pandemic."
        note: "It's not recommended to compare levels across countries; local differences in categories could be misleading."
        originUrl: "ourworldindata.org/coronavirus"
        minTime: "earliest"
        maxTime: "latest"
        hideAnnotationFieldsInTitle: { "time": True }
        addCountryMode: "change-country"

title:
  title: Mobility during COVID-19 pandemic
  title_variant: by place
defaultSelection:
  - United Kingdom
topic_tags:
  - COVID-19

dimensions:
  - slug: place
    name: Place
    choices:
      - slug: all
        name: All places
        description: "See all places"
      - slug: Grocery and pharmacy
        name: Grocery and pharmacy
        description: Grocery markets, food warehouses, farmers markets, specialty food shops, drug stores, and pharmacies.
      - slug: Parks
        name: Parks
        description: Local parks, national parks, public beaches, marinas, dog parks, plazas, and public gardens
      - slug: Residential
        name: Residential
        description: Places of residence
      - slug: Retail and recreation
        name: Retail and recreation
        description: Restaurants, cafes, shopping centers, theme parks, museums, libraries, and movie theaters
      - slug: Transit stations
        name: Transit stations
        description: Public transport hubs such as subway, bus, and train stations
      - slug: Workplaces
        name: Workplaces
        description: Places of work

views:
  - dimensions:
      place: all
    indicators:
      y:
        - "google_mobility#trend__place_grocery_and_pharmacy"
        - "google_mobility#trend__place_parks"
        - "google_mobility#trend__place_residential"
        - "google_mobility#trend__place_retail_and_recreation"
        - "google_mobility#trend__place_transit_stations"
        - "google_mobility#trend__place_workplaces"

    config:
      title: "How did the number of visitors change since the beginning of the pandemic?"
