definitions:
  common_views:
    - config_base:
        originUrl: ourworldindata.org/coronavirus
        chartTypes: ["StackedDiscreteBar"]
        note: "{definitions.note}."
        sortBy: column
  note: |-
    COVAX is a worldwide initiative aimed at equitable access to COVID-19 vaccines. It is directed by Gavi, CEPI, and the WHO
  subtitle: |-
    Doses donated to the COVAX initiative by each country or region
  title: |-
    COVID-19 vaccine doses donated to COVAX
  display_delivered: &display_delivered
    color: "#3182bd"
    name: "Shipped by COVAX"
  display_only_donated: &display_only_donated
    color: "#9ecae1"
    name: "Donated to COVAX"
  display_only_announced: &display_only_announced
    color: "#deebf7"
    name: "Donations to COVAX announced"

title:
  title: Vaccine doses donated to COVAX
  title_variant: "COVID-19 vaccine doses that were donated to COVAX by countries"
default_selection:
  - France
  - Spain
  - Sweden
  - United States
  - Canada
  - Norway
  - New Zealand
  - United Kingdom
  - Denmark
  - Switzerland
  - Italy
  - Germany
  - Portugal
  - Belgium
  - European Union
  - Japan
  - Netherlands
  - Finland
  - Hong Kong
  - Ireland
  - Austria
  - Brazil
  - Slovakia
  - Slovenia
  - South Korea
  - Mexico
  - Greece
  - European Union (27)
topic_tags:
  - COVID-19

dimensions:
  - slug: normalize
    name: Normalization
    choices:
      - slug: absolute
        name: Absolute numbers
        description: null
      - slug: per_capita
        name: Per capita
        description: Normalized by people living in the country
      - slug: per_dose
        name: Per dose administered
        description: Normalized by total doses administered domestically
      - slug: per_gdp
        name: Per million dollars of GDP
        description: Normalized by the GDP of the country (in million dollars)

views:
  - dimensions:
      normalize: absolute
    indicators:
      y:
        - catalogPath: "covax#delivered"
          display: *display_delivered
        - catalogPath: "covax#only_donated"
          display: *display_only_donated
        - catalogPath: "covax#only_announced"
          display: *display_only_announced
    config:
      title: "{definitions.title}"
      subtitle: "{definitions.subtitle}."
      sortColumnSlug: "covax#delivered"

  - dimensions:
      normalize: per_capita
    indicators:
      y:
        - catalogPath: "covax#delivered_per_capita"
          display: *display_delivered
        - catalogPath: "covax#only_donated_per_capita"
          display: *display_only_donated
        - catalogPath: "covax#only_announced_per_capita"
          display: *display_only_announced

    config:
      title: "{definitions.title}, per capita"
      subtitle: "{definitions.subtitle}, per person living in the donating country or region."
      sortColumnSlug: "covax#delivered_per_capita"

  - dimensions:
      normalize: per_dose
    indicators:
      y:
        - catalogPath: "covax#delivered_per_used"
          display: *display_delivered
        - catalogPath: "covax#only_donated_per_used"
          display: *display_only_donated
        - catalogPath: "covax#only_announced_per_used"
          display: *display_only_announced
    config:
      title: "{definitions.title}, per dose administered"
      subtitle: "{definitions.subtitle}, per dose administered domestically."
      sortColumnSlug: "covax#delivered_per_used"

  - dimensions:
      normalize: per_gdp
    indicators:
      y:
        - catalogPath: "covax#delivered_per_gdp"
          display: *display_delivered
        - catalogPath: "covax#only_donated_per_gdp"
          display: *display_only_donated
        - catalogPath: "covax#only_announced_per_gdp"
          display: *display_only_announced
    config:
      title: "{definitions.title}, per million dollars of GDP"
      subtitle: "{definitions.subtitle}, per million dollars of GDP of the donating country or region."
      note: |-
        {definitions.note}. Gross domestic product is expressed in U.S. Dollars; it is sourced from the World Bank and OECD.
      sortColumnSlug: "covax#delivered_per_gdp"
