definitions:
  config: &config
    $schema: https://files.ourworldindata.org/schemas/grapher-schema.006.json
    hideAnnotationFieldsInTitle:
      entity: true
      time: true
      changeInPrefix: true
    originUrl: ourworldindata.org/coronavirus

title:
  title: COVID-19 vaccines administered
  titleVariant: ""
defaultSelection:
  - Belgium
  - Canada
  - France
  - Israel
  - Italy
  - Netherlands
  - Spain
  - United Kingdom
  - United States
topicTags:
  - COVID-19

dimensions:
  - slug: indicator
    name: Indicator
    choices:
      - slug: total
        name: All doses
        description: All doses, including booster doses
      - slug: booster
        name: Booster doses
        description: null
  - slug: normalize
    name: Normalize
    choices:
      - slug: absolute
        name: Absolute number
        description: null
      - slug: per_capita
        name: Per hundred people
        description: Normalized by hunded people living in the country or region

views:
  - dimensions:
      indicator: total
      normalize: absolute
    indicators:
      y: "vaccinations_global#total_vaccinations"
    config: *config
  - dimensions:
      indicator: total
      normalize: per_capita
    indicators:
      y: "vaccinations_global#total_vaccinations_per_hundred"
    config: *config
  - dimensions:
      indicator: booster
      normalize: absolute
    indicators:
      y: "vaccinations_global#total_boosters"
    config: *config
  - dimensions:
      indicator: booster
      normalize: per_capita
    indicators:
      y: "vaccinations_global#total_boosters_per_hundred"
    config: *config
