definitions:
  common_views:
    - config:
        hideAnnotationFieldsInTitle:
          entity: true
          time: true
          changeInPrefix: true
        originUrl: ourworldindata.org/coronavirus

title:
  title: COVID-19 hospitalizations
  titleVariant: ""
defaultSelection:
  - Belgium
  - Canada
  - France
  - Israel
  - Italy
  - Netherlands
  - Spain
  - United Kingdom
  - United States
topicTags:
  - COVID-19

dimensions:
  - slug: type
    name: Type
    choices:
      - slug: hospital
        name: Hospitalizations
        description: null
      - slug: icu
        name: Intensive care unit (ICU)
        description: null

  - slug: measure
    name: Measure
    choices:
      - slug: patients
        name: Patients
        description: Current number of patients in hospital or ICU
      - slug: admissions
        name: Weekly admissions
        description: New weekly admissions to the hospital or ICU

  - slug: normalize
    name: Normalization
    choices:
      - slug: absolute
        name: Absolute number
        description: null
      - slug: per_capita
        name: Per million people
        description: Normalized by million people living in the country or region

views:
  - dimensions:
      type: hospital
      measure: patients
      normalize: absolute
    indicators:
      y: "hospital#daily_occupancy_hosp"
  - dimensions:
      type: hospital
      measure: patients
      normalize: per_capita
    indicators:
      y: "hospital#daily_occupancy_hosp_per_1m"
  - dimensions:
      type: hospital
      measure: admissions
      normalize: absolute
    indicators:
      y: "hospital#weekly_admissions_hosp"
  - dimensions:
      type: hospital
      measure: admissions
      normalize: per_capita
    indicators:
      y: "hospital#weekly_admissions_hosp_per_1m"

  - dimensions:
      type: icu
      measure: patients
      normalize: absolute
    indicators:
      y: "hospital#daily_occupancy_icu"
  - dimensions:
      type: icu
      measure: patients
      normalize: per_capita
    indicators:
      y: "hospital#daily_occupancy_icu_per_1m"
  - dimensions:
      type: icu
      measure: admissions
      normalize: absolute
    indicators:
      y: "hospital#weekly_admissions_icu"
  - dimensions:
      type: icu
      measure: admissions
      normalize: per_capita
    indicators:
      y: "hospital#weekly_admissions_icu_per_1m"
