definitions:
  config: &config_base
    originUrl: ourworldindata.org/coronavirus
    hideAnnotationFieldsInTitle:
      time: true

title:
  title: COVID-19 vaccines
  titleVariant: "breakdowns"
defaultSelection:
  - High-income countries
  - Upper-middle-income countries
  - Lower-middle-income countries
  - Low-income countries

topicTags:
  - COVID-19

dimensions:
  - slug: breakdown
    name: Breakdown
    choices:
      - slug: income_group
        name: Income group
        description: "Doses per 100 people by income group"
      - slug: manufacturer
        name: Manufacturer
        description: "Doses administered by vaccine manufacturer"

views:
  - dimensions:
      breakdown: income_group
    indicators:
      y: "vaccinations_global#total_vaccinations_per_hundred"
    config:
      <<: *config_base
      addCountryMode: "disabled"
      selectedEntityNames:
        - High-income countries
        - Upper-middle-countriesincome countries
        - Lower-middle-income countries
        - Low-income
      selectedEntityColors:
        High-income countries: "#0D8553"
        Upper-middle-income countries: "#A1CB81"
        Lower-middle-income countries: "#DF9FDB"
        Low-income countries: "#974E94"
  - dimensions:
      breakdown: manufacturer
    indicators:
      y:
        - "vaccinations_manufacturer#total_vaccinations__vaccine_pfizer_biontech"
        - "vaccinations_manufacturer#total_vaccinations__vaccine_moderna"
        - "vaccinations_manufacturer#total_vaccinations__vaccine_oxford_astrazeneca"
        - "vaccinations_manufacturer#total_vaccinations__vaccine_johnson_and_johnson"
        - "vaccinations_manufacturer#total_vaccinations__vaccine_sputnik_v"
        - "vaccinations_manufacturer#total_vaccinations__vaccine_sinovac"
        - "vaccinations_manufacturer#total_vaccinations__vaccine_sinopharm_beijing"
        - "vaccinations_manufacturer#total_vaccinations__vaccine_cansino"
        - "vaccinations_manufacturer#total_vaccinations__vaccine_novavax"
        - "vaccinations_manufacturer#total_vaccinations__vaccine_covaxin"
        - "vaccinations_manufacturer#total_vaccinations__vaccine_medicago"
        - "vaccinations_manufacturer#total_vaccinations__vaccine_sanofi_gsk"
        - "vaccinations_manufacturer#total_vaccinations__vaccine_skycovione"
        - "vaccinations_manufacturer#total_vaccinations__vaccine_valneva"
    config:
      <<: *config_base
      chartTypes: ["StackedArea"]
      selectedEntityNames:
        - European Union (27)
