definitions:
  config: &config
    $schema: https://files.ourworldindata.org/schemas/grapher-schema.006.json
    hideAnnotationFieldsInTitle:
      entity: true
      time: true
      changeInPrefix: true
    originUrl: ourworldindata.org/coronavirus

title:
  title: COVID-19 vaccine boosters administered
  titleVariant: ""
defaultSelection:
  - Belgium
  - Canada
  - France
  - Israel
  - Italy
  - Netherlands
  - Spain
  - United Kingdom
  - United States
topicTags:
  - COVID-19

dimensions:
  - slug: normalize
    name: Indicator
    choices:
      - slug: absolute
        name: Absolute number
        description: null
      - slug: per_capita
        name: Per million people
        description: null

views:
  - dimensions:
      normalize: absolute
    indicators:
      y: "vaccinations_global#total_boosters"
    config: *config
  - dimensions:
      normalize: per_capita
    indicators:
      y: "vaccinations_global#total_boosters_per_hundred"
    config: *config
