definitions:
  table: grapher/excess_mortality/latest/excess_mortality/excess_mortality

title:
  title: "Excess mortality"
  titleVariant: "Cumulative deaths from all causes compared to projection based on previous years"
defaultSelection:
  - Russia
  - United States
  - Brazil
  - Mexico
  - Iran
  - Peru
topicTags:
  - COVID-19

dimensions:
  - slug: normalize
    name: Normalization
    choices:
      - slug: absolute
        name: None
        description: null
      - slug: per_capita
        name: Per million people
        description: null
      - slug: percentage
        name: Percentage
        description: null

views:
  - dimensions:
      normalize: absolute
    indicators:
      y: "{definitions.table}#cum_excess_proj_all_ages"
  - dimensions:
      normalize: per_capita
    indicators:
      y: "{definitions.table}#cum_excess_per_million_proj_all_ages"
  - dimensions:
      normalize: percentage
    indicators:
      y: "{definitions.table}#cum_p_proj_all_ages"
