definitions:
  config: &config
    $schema: https://files.ourworldindata.org/schemas/grapher-schema.006.json
    hideAnnotationFieldsInTitle:
      entity: true
      time: true
      changeInPrefix: true
    originUrl: ourworldindata.org/coronavirus

title:
  title: "Excess mortality"
  titleVariant: "Cumulative deaths from all causes compared to projection based on previous years"
defaultSelection:
  - Russia
  - United States
  - Brazil
  - Mexico
  - Iran
  - Peru
topicTags:
  - COVID-19

dimensions:
  - slug: normalize
    name: Normalization
    choices:
      - slug: absolute
        name: None
        description: null
      - slug: per_capita
        name: Per million people
        description: null
      - slug: percentage
        name: Percentage
        description: null

views:
  - dimensions:
      normalize: absolute
    indicators:
      y: "excess_mortality#cum_excess_proj_all_ages"
    config: *config
  - dimensions:
      normalize: per_capita
    indicators:
      y: "excess_mortality#cum_excess_per_million_proj_all_ages"
    config: *config
  - dimensions:
      normalize: percentage
    indicators:
      y: "excess_mortality#cum_p_proj_all_ages"
    config: *config
