# definitions:
#   common_views:
#     - config:

config:
  explorerTitle: Animal Welfare
  isPublished: true
  entityType: country
  explorerSubtitle: Explore the number of animals slaughtered and welfare impacts.
  selection:
    - World
    - United States
    - China
    - India
    - Brazil
    - United Kingdom
  # subNavId:
  # subNavCurrentId:
  # wpBlockId: "58184"  # TODO: Is this needed?
  hasMapTab: true
  # hideAnnotationFieldsInTitle: true

dimensions:
  - slug: metric
    name: Metric
    choices:
      - slug: n_animals_killed
        name: Animals slaughtered
    presentation:
      type: dropdown
  - slug: animal
    name: Animal
    choices:
      - slug: chicken
        name: Chickens
      - slug: pig
        name: Pigs
      - slug: sheep
        name: Sheep
      - slug: goat
        name: Goats
      - slug: cattle
        name: Cows
      # TODO: Either continue, or fill out programmatically.
    presentation:
      type: dropdown

# views:
#   - dimensions:
#       metric: n_animals_killed
#       animal: chicken
#     indicators:
#       y:
#         - catalogPath: animals_used_for_food#chickens_killed
