"""Logic and code to combine multiple charts (MDIMs or Explorers) into a single one.

Additional: combine dimensions (using raw dictionaries)
"""

from collections.abc import Mapping
from copy import deepcopy
from typing import Any, TypeVar, overload

import pandas as pd
from structlog import get_logger

from etl.viz.chart.core.utils import create_chart_from_config
from etl.viz.chart.model.core import Chart
from etl.viz.chart.model.dimension import Dimension, DimensionChoice
from etl.viz.chart.utils import records_to_dictionary
from etl.viz.explorer import Explorer

log = get_logger()

# Dimension added when the combined charts have overlapping views and the caller gave no
# `chart_dimension_slug` / `chart_dimension_name`. The slug ends up in multidim and explorer URLs.
DEFAULT_SOURCE_DIMENSION_SLUG = "chart__slug"
DEFAULT_SOURCE_DIMENSION_NAME = "Chart"

# Define type variables to use in overloads
T = TypeVar("T", bound=Chart)
E = TypeVar("E", bound=Explorer)


# COMBINE DIMENSIONS
def combine_config_dimensions(
    config_dimensions: list[dict[str, Any]],
    config_dimensions_yaml: list[dict[str, Any]],
    choices_top: bool = False,
    dimensions_top: bool = False,
):
    """Combine the dimension configuration from the YAML file with the one generated programmatically.

    There are various strategies that we could follow here, but currently:

    - We consider the union of config_dimensions (returned by expander.build_dimensions) nad config_dimensions_yaml.
    - These are kept as-is, unless they are in the YML config, in which case they are overwritten.

    Other possible strategies:

    - We could do the reverse, and only consider the fields from config_dimensions_yaml. I'm personally unsure when this could be valuable.


    Arguments
    ---------
    config_dimensions: List[Dict[str, Any]]
        Generated by expander.build_dimensions.
    config_dimensions_yaml:  List[Dict[str, Any]]
        From the YAML file.
    choices_top: bool
        Set to True to place the choices from `config_dimensions` first.
    dimensions_top: bool
        Set to True to place the dimensions from `config_dimensions` first.

    TODO:

        - I think we need to add more checks to ensure that there is nothing weird being produced here.
    """

    config_dimensions_combined = deepcopy(config_dimensions)
    dims_overwrite = records_to_dictionary(config_dimensions_yaml, "slug")

    # Overwrite dimensions
    for dim in config_dimensions_combined:
        slug_dim = dim["slug"]
        if slug_dim in dims_overwrite:
            # Get dimension data to overwrite, remove it from dictionary
            dim_overwrite = dims_overwrite.pop(slug_dim)

            # Overwrite dimension name
            dim["name"] = dim_overwrite.get("name", dim["name"])

            # Overwrite presentation
            if "presentation" in dim_overwrite:
                dim["presentation"] = dim_overwrite["presentation"]

            # Overwrite description
            if "description" in dim_overwrite:
                dim["description"] = dim_overwrite["description"]

            # Overwrite choices
            if "choices" in dim_overwrite:
                choices_overwrite = records_to_dictionary(
                    dim_overwrite["choices"],
                    "slug",
                )
                assert "choices" in dim, (
                    f"Choices not found in dimension: {dim}! This is rare, please report this issue!"
                )
                for choice in dim["choices"]:
                    slug_choice = choice["slug"]
                    if slug_choice in choices_overwrite:
                        # Get dimension data to overwrite, remove it from dictionary
                        choice_overwrite = choices_overwrite.pop(slug_choice)

                        # Overwrite choice name
                        choice["name"] = choice_overwrite.get("name", dim["name"])
                        # Overwrite choice description
                        description = choice_overwrite.get("description", choice.get("description"))
                        if description is not None:
                            choice["description"] = description
                        # Overwrite group
                        group = choice_overwrite.get("group")
                        if group is not None:
                            choice["group"] = group

                # Handle choices from YAML not present in config_dimensions
                if choices_overwrite:
                    missing_choices = []
                    for slug, values in choices_overwrite.items():
                        choice = {"slug": slug, **values}
                        missing_choices.append(choice)

                    if choices_top:
                        dim["choices"] += missing_choices
                    else:
                        dim["choices"] = missing_choices + dim["choices"]

                # Sort choices based on how these appear in the YAML file (only if dimensions_top is False)
                if not choices_top:
                    dim["choices"] = _order(dim_overwrite["choices"], dim["choices"])

    # Handle dimensions from YAML not present in config_dimensions
    if dims_overwrite:
        missing_dims = []
        for slug, values in dims_overwrite.items():
            dim = {"slug": slug, **values}
            missing_dims.append(dim)

        if dimensions_top:
            config_dimensions_combined += missing_dims
        else:
            config_dimensions_combined = missing_dims + config_dimensions_combined

    # Sort dimensions based on how these appear in the YAML file (only if dimensions_top is False)
    if not dimensions_top:
        config_dimensions_combined = _order(config_dimensions_yaml, config_dimensions_combined)

    return config_dimensions_combined


def _order(config_yaml, config_combined):
    # Build score
    score = {record["slug"]: i for i, record in enumerate(config_yaml)}
    # Split: those that need ordering, those that don't
    config_sort = [record for record in config_combined if record["slug"] in score]
    config_others = [record for record in config_combined if record["slug"] not in score]

    # Order if applicable
    config_sort = sorted(
        config_sort,
        key=lambda x: score.get(x["slug"], 100),
    )

    return config_sort + config_others


@overload
def combine_charts(
    charts: list[E],
    chart_name: str | None = None,
    catalog_path: str | None = None,
    config: dict[str, Any] | None = None,
    dependencies: set[str] | None = None,
    force_chart_dimension: bool = False,
    chart_dimension_name: str | None = None,
    chart_dimension_slug: str | None = None,
    chart_choices_names: list[str] | None = None,
    is_explorer: bool | None = None,
    _slug_changes_out: dict | None = None,
) -> E: ...


@overload
def combine_charts(
    charts: list[T],
    chart_name: str | None = None,
    catalog_path: str | None = None,
    config: dict[str, Any] | None = None,
    dependencies: set[str] | None = None,
    force_chart_dimension: bool = False,
    chart_dimension_name: str | None = None,
    chart_dimension_slug: str | None = None,
    chart_choices_names: list[str] | None = None,
    is_explorer: bool | None = None,
    _slug_changes_out: dict | None = None,
) -> T: ...


# COMBINE CHARTS
def combine_charts(
    charts: list[Chart] | list[Explorer],
    chart_name: str | None = None,
    catalog_path: str | None = None,
    config: dict[str, Any] | None = None,
    dependencies: set[str] | None = None,
    force_chart_dimension: bool = False,
    chart_dimension_name: str | None = None,
    chart_dimension_slug: str | None = None,
    chart_choices_names: list[str] | None = None,
    is_explorer: bool | None = None,
    _slug_changes_out: dict | None = None,
) -> Chart | Explorer:
    """Combine multiple charts (MDIMs or Explorers) into a single one.

    This function serves as a unified interface to combine either Explorers
    or MDIMs (Charts), abstracting the common logic between the two.

    Args:
        charts:
            List of charts (either all MDIMs or all Explorers) to combine
        chart_name:
            Name of the resulting combined chart. This is used to define the `catalog_path` of the resulting combined chart (re-uses the catalog_path of the first chart, and replaced its short_name with the `chart_name`). Alternatively, you can use `catalog_path` to force a specific path.
        catalog_path:
            Force specific catalog path, regardless of `chart_name`.
        config:
            Configuration for the combined chart
        dependencies:
            Set of dependencies for the combined chart
        force_chart_dimension:
            If True, adds a dimension to identify the source chart even if there are no duplicate views
        chart_dimension_slug:
            Slug for the dimension that identifies the source chart. If None, defaults to "chart__slug".
        chart_dimension_name:
            Name for the dimension that identifies the source chart. If None, defaults to "Chart".
        chart_choices_names:
            Names for the choices in the source dimension (should match the length of charts)
        is_explorer:
            Force the result to be an Explorer (True) or MDIM (False). If None (default), inferred from the input charts.
        _slug_changes_out:
            Internal. When a non-None dict is passed, it is mutated in-place with
            the slug changes produced by conflict resolution. Structure:
            ``{chart_id: {dimension_slug: {original_slug: renamed_slug}}}``.
            Used by ``create_chart`` to remap per-table ``choice_renames``.

    Returns:
        A combined Chart or Explorer, matching the type of the input charts

    Notes:
        - All charts must have the same dimensions structure (slug, name, etc.)
        - Choice conflicts are resolved by renaming conflicting choices
        - If duplicate views exist, a source dimension is automatically added
    """
    # Check that there are at least 2 charts to combine
    assert len(charts) > 0, "No charts to combine."
    assert len(charts) > 1, "At least two charts should be provided."

    # Check that either chart_name or catalog_path is provided
    if chart_name is None and catalog_path is None:
        raise ValueError("Either chart_name or catalog_path must be provided.")

    # Determine chart type if not specified
    if is_explorer is None:
        is_explorer = all(isinstance(c, Explorer) for c in charts)
        if not (is_explorer or all(not isinstance(c, Explorer) for c in charts)):
            raise ValueError("All charts must be of the same type (either all Explorers or all Charts)")

    # Set appropriate default dimension name based on chart type
    if chart_dimension_name is None:
        chart_dimension_name = DEFAULT_SOURCE_DIMENSION_NAME
    if chart_dimension_slug is None:
        chart_dimension_slug = DEFAULT_SOURCE_DIMENSION_SLUG

    # Check that all charts have the same dimensions structure
    chart_dims = None
    for chart in charts:
        dimensions_flatten = [{k: v for k, v in dim.to_dict().items() if k != "choices"} for dim in chart.dimensions]
        if chart_dims is None:
            chart_dims = dimensions_flatten
        else:
            assert chart_dims == dimensions_flatten, (
                "Dimensions are not the same across charts. Please review that dimensions are listed in the same order, have the same slugs, names, description, etc."
            )

    # Checkbox dimensions are only safe to combine when all charts share the same
    # definition (same slug/name/presentation AND same choice set). When they match, the
    # merge is structurally identical to a 2-choice radio. The structural equality of
    # everything except `choices` was already asserted above (see `dimensions_flatten`);
    # we additionally require the choice slugs to match, since `_combine_dimensions`
    # currently rebuilds the choice list by union and that would silently flip a checkbox
    # into a 3+-choice widget if the sub-charts disagreed on the off/on slugs.
    for dim in charts[0].dimensions:
        if dim.ui_type == "checkbox" and is_explorer:
            ref_slugs = sorted(dim.choice_slugs)
            for other in charts[1:]:
                other_dim = next((d for d in other.dimensions if d.slug == dim.slug), None)
                if other_dim is None or sorted(other_dim.choice_slugs) != ref_slugs:
                    raise NotImplementedError(
                        f"Checkbox dimension '{dim.slug}' has different choices across "
                        "charts — merging is not supported. Ensure every sub-chart "
                        "declares the same checkbox slug, choices, and `choice_slug_true`."
                    )

    # Detect duplicate views + save dependencies
    seen_dims = set()
    has_duplicate_views = False
    dependencies_combined = set()
    for chart in charts:
        # duplicate views within a chart
        chart.check_duplicate_views()
        # duplicate views across charts
        for view in chart.views:
            dims = tuple(view.dimensions.items())
            if dims in seen_dims:
                has_duplicate_views = True
                break
            seen_dims.add(dims)

        # Save dependencies from each chart
        dependencies_combined |= chart.dependencies

    # Add chart dimension if needed
    if has_duplicate_views or force_chart_dimension:
        for i, chart in enumerate(charts):
            if chart_choices_names is not None:
                assert len(chart_choices_names) == len(charts), (
                    "Length of chart_choices_names must match the number of charts"
                )
                choice_name = chart_choices_names[i]
            else:
                choice_name = (chart.title or {}).get("title", chart.short_name)

            dimension_source = Dimension(
                slug=chart_dimension_slug,
                name=chart_dimension_name,
                choices=[
                    DimensionChoice(slug=chart.short_name, name=choice_name),
                ],
            )
            chart.dimensions = [dimension_source] + chart.dimensions
            for v in chart.views:
                v.dimensions[chart_dimension_slug] = chart.short_name

    # Create dictionary with charts for tracking
    charts_by_id = {str(i): deepcopy(chart) for i, chart in enumerate(charts)}

    # Build dataframe with all choices
    df_choices, cols_choices = _build_df_choices(charts_by_id)

    # Combine dimensions (use first chart as template)
    dimensions = _combine_dimensions(
        df_choices=df_choices,
        cols_choices=cols_choices,
        chart=charts[0].copy(),
    )

    # Track modifications (useful later for views)
    choice_slug_changes = _extract_choice_slug_changes(df_choices)

    # Update views based on changes to choice slugs
    charts_by_id = _update_choice_slugs_in_views(choice_slug_changes, charts_by_id)

    # Collect all views
    views = []
    for _, chart in charts_by_id.items():
        views.extend(chart.views)

    # Create catalog path
    if isinstance(catalog_path, str):
        assert "#" in catalog_path, "Catalog path must contain a '#' to separate the base path from the chart name."
        catalog_path_new = catalog_path
        chart_name_new = catalog_path_new.split("#")[-1]
    else:
        assert isinstance(charts[0].catalog_path, str), "Catalog path is not set. Please set it before saving."
        assert chart_name is not None, "Chart name must be provided if catalog_path is not set."
        catalog_path_new = charts[0].catalog_path.split("#")[0] + "#" + chart_name
        chart_name_new = chart_name

    # Ensure config has minimal required fields
    if config is None:
        cconfig = {}
    else:
        cconfig = deepcopy(config)

    # Make sure there is title and default_selection. If not given, use default values.
    default_title = {
        "title": f"Combined Chart: {chart_name_new}",
        "title_variant": "Use a YAML to define these attributes",
    }
    if not is_explorer:
        if "title" not in cconfig:
            cconfig["title"] = default_title
        else:
            cconfig["title"] = {**default_title, **cconfig["title"]}
        if "default_selection" not in cconfig:
            cconfig["default_selection"] = charts[0].default_selection
    else:
        if "config" not in cconfig:
            cconfig["config"] = {}
        if "explorerTitle" not in cconfig["config"]:
            cconfig["config"]["explorerTitle"] = default_title["title"]
        if "explorerSubtitle" not in cconfig["config"]:
            cconfig["config"]["explorerSubtitle"] = default_title["title_variant"]

    # Set dimensions and views
    # cconfig["dimensions"] = dimensions
    cconfig["dimensions"] = combine_config_dimensions(
        [d.to_dict() for d in dimensions],
        cconfig.get("dimensions", []),
    )
    # Hand-listed YAML views (from the user's config) belong here — alongside the views
    # accumulated from sub-charts. Sub-chart views are View instances; YAML views
    # are dicts. `create_chart_from_config` (via Explorer.from_dict / Chart.from_dict)
    # accepts both shapes.
    yaml_views = cconfig.get("views") or []
    cconfig["views"] = views + list(yaml_views)

    # Create the combined chart
    combined = create_chart_from_config(
        config=cconfig,
        dependencies=dependencies if dependencies is not None else set(),
        catalog_path=catalog_path_new,
        validate_schema=True if not is_explorer else False,
        explorer=is_explorer,
        dependencies_combined=dependencies_combined,
    )

    # Log any conflicts that were resolved
    df_conflict = df_choices.loc[df_choices["in_conflict"]]
    if not df_conflict.empty:
        log.warning("Choice slug conflicts resolved")
        for (dimension_slug, choice_slug), group in df_conflict.groupby(["dimension_slug", "slug_original"]):
            log.warning(f"(dimension={dimension_slug}, choice={choice_slug})")
            for _, subgroup in group.groupby("choice_slug_id"):
                chart_ids = subgroup["chart_id"].unique().tolist()
                chart_names = [charts_by_id[i].short_name for i in chart_ids]
                record = subgroup[cols_choices].drop_duplicates().to_dict("records")
                assert len(record) == 1, "Unexpected, please report!"
                log.warning(f" Charts {chart_names} map to {record[0]}")

    # Expose slug changes to caller if requested (used by create_chart
    # to remap per-table choice_renames after combining).
    if _slug_changes_out is not None:
        _slug_changes_out.update(choice_slug_changes)

    return combined


def _extract_choice_slug_changes(df_choices) -> dict[str, Any]:
    # Track modifications (useful later for views)
    slug_changes = (
        df_choices.loc[df_choices["in_conflict"]]
        .groupby(["chart_id", "dimension_slug"])
        .apply(lambda x: dict(zip(x["slug_original"], x["slug"])), include_groups=False)
        .unstack("chart_id")
        .to_dict()
    )

    return slug_changes


def _combine_dimensions(df_choices: pd.DataFrame, cols_choices: list[str], chart: Explorer | Chart) -> list[Dimension]:
    """Combine dimensions from different explorers"""
    # Dimension bucket
    dimensions = chart.dimensions.copy()

    # Drop duplicates
    df_choices = df_choices.drop_duplicates(subset=cols_choices + ["slug", "dimension_slug"])

    # Iterate over each dimension and update the list of choices
    for dimension in dimensions:
        df_dim_choices = df_choices.loc[
            df_choices["dimension_slug"] == dimension.slug, cols_choices + ["slug"]
        ].drop_duplicates()

        assert len(df_dim_choices) == df_dim_choices["slug"].nunique(), (
            f"Duplicate slugs in dimension {dimension.slug} choices."
        )

        # Raw choices
        choices = df_dim_choices.to_dict("records")

        # Build choices
        dimension.choices = [DimensionChoice.from_dict(c) for c in choices]

    return dimensions


def _update_choice_slugs_in_views(choice_slug_changes, charts_by_id) -> Mapping[str, Chart | Explorer]:
    """Access each explorer, and update choice slugs in views"""
    for chart_id, change in choice_slug_changes.items():
        # `change` is the column from `_extract_choice_slug_changes`'s unstacked frame —
        # dimensions with no conflicts in this chart come through as NaN. Drop them;
        # pandas.DataFrame.replace rejects a nested mapping if any top-level value isn't a dict.
        change = {k: v for k, v in change.items() if isinstance(v, dict) and v}
        if not change:
            continue

        # Get chart
        chart = charts_by_id[chart_id]

        # Get views as dataframe for easy processing
        df_views_dimensions = pd.DataFrame([view.dimensions for view in chart.views])

        # FUTURE: this needs to change in order to support checkboxes
        df_views_dimensions = df_views_dimensions.astype("string")

        # Process views
        df_views_dimensions = df_views_dimensions.replace(change)

        # Bring back views to charts
        views_dimensions = df_views_dimensions.to_dict("records")
        for view, view_dimensions in zip(chart.views, views_dimensions):
            # cast keys to str to satisfy type requirements
            view.dimensions = {str(key): value for key, value in view_dimensions.items()}
    return charts_by_id


def _build_df_choices(charts_by_id: Mapping[str, Chart | Explorer]) -> tuple[pd.DataFrame, list[str]]:
    # Collect all choices in a dataframe: choice_slug, choice_name, ..., chart_id, dimension_slug.
    records = []
    for i, explorer in charts_by_id.items():
        for dim in explorer.dimensions:
            for choice in dim.choices:
                records.append(
                    {
                        **choice.to_dict(),
                        "dimension_slug": dim.slug,
                        "chart_id": i,
                    }
                )
    # This needs to change to support checkboxes
    df_choices = pd.DataFrame(records).astype("string")

    # Get column names of fields from choice objects
    cols_choices = [col for col in df_choices.columns if col not in ["slug", "chart_id", "dimension_slug"]]

    # For each choice slug, assign an ID (choice_slug_id) that identifies that "slug flavour". E.g. if a slug has different names (or descriptions) across explorers, each "flavour" will have a different ID. This will be useful later to identify conflicts & rename slugs.
    df_choices["choice_slug_id"] = (
        df_choices.groupby(["dimension_slug", "slug"], group_keys=False)
        .apply(
            lambda g: pd.Series(
                pd.factorize(pd.Series(zip(*[g[c] for c in cols_choices])))[0],
                index=g.index,
            ),
            include_groups=False,
        )
        .astype("string")
    )
    # Mark choice slugs as "in conflict": A choice slug maps to different names (or descriptions) across explorers
    df_choices["in_conflict"] = (
        df_choices.groupby(["dimension_slug", "slug"], as_index=False)["choice_slug_id"].transform("nunique").ne(1)
    )

    # Mark choices as duplicates: Same choice properties for a given dimension
    df_choices["duplicate"] = df_choices.duplicated(subset=cols_choices + ["slug", "dimension_slug"])

    # Drop duplicates, except those that are in conflict
    df_choices = df_choices.loc[~df_choices["duplicate"] | df_choices["in_conflict"]]

    # Rename slugs for choices that are duplicates. 'slug' for final slugs, 'slug_original' keeps the original slug
    df_choices.loc[:, "slug_original"] = df_choices.loc[:, "slug"].copy()
    mask = df_choices["in_conflict"]
    df_choices.loc[mask, "slug"] = df_choices.loc[mask, "slug"] + "__" + df_choices.loc[mask, "choice_slug_id"]

    return df_choices, cols_choices
