"""Hand-written parameter types for Collection methods.

These types describe Python method parameters (e.g. `Collection.group_views`) and are NOT
derived from any JSON schema, so they live here instead of in the auto-generated
`schema_types.py` (which is fully regenerated by `scripts/generate_schema_types.py`).
"""

from typing import Any, TypedDict

from etl.collection.model.schema_types import ViewConfigParam, ViewMetadataParam


class _GroupViewsConfigRequired(TypedDict):
    """Required fields for GroupViewsConfig."""

    dimension: str  # Slug of the dimension that contains the choices to group
    choice_new_slug: str  # The slug for the newly created choice


class GroupViewsConfig(_GroupViewsConfigRequired, total=False):
    """Configuration for group_views method parameters."""

    # Optional fields
    choices: list[str]  # Slugs of the choices to group. If not provided, all choices are used
    view_config: ViewConfigParam  # The view config for the new choice
    view_metadata: ViewMetadataParam  # The metadata for the new view
    replace: bool  # If True, the original choices will be removed and replaced with the new choice
    overwrite_dimension_choice: (
        bool  # If True and choice_new_slug already exists, views created here will overwrite existing ones
    )


GroupViewsParam = GroupViewsConfig | dict[str, Any]


def create_group_config(
    dimension: str,
    choice_new_slug: str,
    *,
    choices: list[str] | None = None,
    view_config: ViewConfigParam | None = None,
    view_metadata: ViewMetadataParam | None = None,
    replace: bool = False,
    overwrite_dimension_choice: bool = False,
) -> GroupViewsConfig:
    """Helper function to create a GroupViewsConfig with proper typing and autocompletion.

    Args:
        dimension: Slug of the dimension that contains the choices to group
        choice_new_slug: The slug for the newly created choice
        choices: Slugs of the choices to group. If not provided, all choices are used
        view_config: The view config for the new choice
        view_metadata: The metadata for the new view
        replace: If True, the original choices will be removed and replaced with the new choice
        overwrite_dimension_choice: If True and choice_new_slug already exists, views created here will overwrite existing ones

    Returns:
        A properly typed GroupViewsConfig dictionary

    Example:
        >>> config = create_group_config(
        ...     dimension="sex",
        ...     choice_new_slug="combined",
        ...     choices=["male", "female"],
        ...     view_config={"title": "Combined view"}
        ... )
    """
    result: GroupViewsConfig = {
        "dimension": dimension,
        "choice_new_slug": choice_new_slug,
    }

    if choices is not None:
        result["choices"] = choices
    if view_config is not None:
        result["view_config"] = view_config
    if view_metadata is not None:
        result["view_metadata"] = view_metadata
    if replace:
        result["replace"] = replace
    if overwrite_dimension_choice:
        result["overwrite_dimension_choice"] = overwrite_dimension_choice

    return result
