definitions:
  common_views:
    # Applies to all views with dimension metric=emigrants, unless overridden
    - dimensions:
        metric: emigrants
    # Applies to all views with dimension metric=immigrants, unless overridden
    - dimensions:
        metric: immigrants

config:
  explorerTitle: Migration Flows
  explorerSubtitle: Explore global migration data, country-by-country.
  isPublished: true
  selection:
    - United States
    - United Kingdom
    - France
    - Mexico
    - India
    - China
    - Germany
    - Australia
    - Brazil
    - South Africa
  thumbnail: https://ourworldindata.org/app/uploads/2022/03/migration-flows-explorer.png
  subNavId:
  subNavCurrentId:
  hasMapTab: true
  yAxisMin: 0
  hideAnnotationFieldsInTitle: true
  tab: map

dimensions:
  - name: Country
    slug: country_origin_or_dest
  - name: Metric
    slug: indicator
    presentation:
      type: radio
    choices:
      - slug: "immigrants"
        name: "Immigrants: People moving to country"
      - slug: "emigrants"
        name: "Emigrants: People moving away from country"
  - name: Gender
    slug: gender
    presentation:
      type: radio
    choices:
      - slug: "all"
        name: "All migrants"
      - slug: "female"
        name: "Female migrants"
      - slug: "male"
        name: "Male migrants"

views: []
