"""MDIM collection: Global AIDS Update

Generated by MDIM Creator wizard.
"""

from etl.helpers import PathFinder

# Get paths and naming conventions for current step.
paths = PathFinder(__file__)


COMMON_CONFIG = {
    "chartTypes": ['LineChart'],
    "hasMapTab": True,
    "tab": "chart",
}


def run() -> None:
    # Load default collection config
    config = paths.load_collection_config()

    # Load grapher dataset
    ds = paths.load_dataset("unaids")
    tb = ds.read("unaids", load_data=False)

    # Create collection
    c = paths.create_collection(
        config=config,
        tb=tb,
        indicator_names=["aids_deaths", "aids_mortality_1000_pop", "aids_orphans", "art_drop_bf_child_inf", "art_drop_preg_child_inf", "art_none_bf", "art_none_preg_child_inf_preg", "art_start_before_preg_child_inf_bf", "art_start_before_preg_child_inf_preg", "art_start_child_inf_during_preg", "art_start_during_preg_child_inf_bf", "art_start_late_preg_child_inf_bf", "art_start_late_preg_child_inf_preg", "children_exposed_uninfected", "coverage_mothers_receiving_arv", "deaths_averted_art", "deaths_plhiv_all_causes", "hiv_incidence", "hiv_prevalence", "imr", "infections_averted_pmtct", "ipr", "mother_child_inf_bf", "mother_child_inf_preg", "mothers_needing_arv_for_pmtct", "mothers_receiving_arv_for_pmtct", "mtct_rate", "new_infections", "number_plhiv_knowledge_of_status", "number_viral_suppression", "pct_change_aids_deaths_2010", "pct_change_new_infections_2010", "people_receiving_art", "people_unsupp_vl", "percent_art_vl_suppressed", "percent_know_status_on_art", "percent_plwh", "plhiv_knowledge_of_status", "plwh", "viral_load_suppression"],
        dimensions=["age", "sex", "estimate"],
        common_view_config=COMMON_CONFIG,
    )

    # Optional: Edit views programmatically
    # for view in c.views:
    #     pass

    # Save collection
    c.save()
