grapher_schema: "011"

title:
  title: Remittances
  title_variant: ""

default_selection:
  - World
  - India
  - Mexico
  - Philippines
  - Nigeria

default_dimensions:
  metric: share_of_gdp

definitions:
  common_views:
    - config:
        hasMapTab: true
        tab: map
        chartTypes: ["LineChart", "DiscreteBar"]
  definition_remittances: Remittances include personal transfers sent by migrants to their home countries as well as compensation of workers who are employed in an economy where they are not resident. This includes temporary migrant workers (e.g. seasonal workers working in another country) and residents of the country employed by foreign employers (such as embassies or transnational companies).
  definition_remittances_share_of_gdp: This chart shows the share of GDP that is made up of the sum of all remittances sent to this country. If this share is high, it means that remittances are an important source of income in this country.
  definition_remittances_cost_of_sending: This chart shows the average transaction cost as a percentage of total remittances sent from this country to abroad, for a single transaction of USD 200. It is calculated by averaging over the cost of all remittance flows from this country.
  definition_remittances_cost_of_receiving: This chart shows the average transaction cost as a percentage of total remittances sent from abroad to this country, for a single transaction of USD 200. It is calculated by averaging over the cost of all remittance flows into this country.

dimensions:
  - slug: metric
    name: Metric
    choices:
      - slug: share_of_gdp
        name: Remittances as a share of GDP
        description: Personal remittances that are received in a country, as a share of GDP.
      - slug: cost_of_sending
        name: Cost of sending remittances
        description: The average cost of sending remittances abroad, as a share of the amount sent.
      - slug: cost_of_receiving
        name: Cost of receiving remittances
        description: The average cost of receiving remittances from abroad, as a share of the amount sent.
    presentation:
      type: radio

views:
  - dimensions:
      metric: share_of_gdp
    indicators:
      y:
        - catalogPath: wdi#bx_trf_pwkr_dt_gd_zs
    config:
      title: Remittances as a share of GDP
      subtitle: Remittances include money sent by migrants to their home countries and the salaries of employees employed by foreign companies. This received sum is given as a share of [gross domestic product](#dod:gdp) (GDP).
      map:
        colorScale:
          baseColorScheme: BuPu
          binningStrategy: manual
          customNumericValues: [0, 0.1, 0.2, 0.5, 1, 2, 5, 10, 20]
    metadata:
      description_key:
        - "{definitions.definition_remittances}"
        - "{definitions.definition_remittances_share_of_gdp}"

  - dimensions:
      metric: cost_of_sending
    indicators:
      y:
        - catalogPath: wdi#si_rmt_cost_ob_zs
    config:
      title: Average cost of sending remittances from a given country
      subtitle: Remittances include money sent by migrants to their home countries and the salaries of employees employed by foreign companies. Shown is the average transaction cost of sending US$200, given as a percentage of the total.
      map:
        colorScale:
          baseColorScheme: Oranges
          binningStrategy: manual
          customNumericValues: [0, 2, 4, 6, 8, 10, 12, 14, 16]
    metadata:
      description_key:
        - "{definitions.definition_remittances}"
        - "{definitions.definition_remittances_cost_of_sending}"

  - dimensions:
      metric: cost_of_receiving
    indicators:
      y:
        - catalogPath: wdi#si_rmt_cost_ib_zs
    config:
      title: Average cost of receiving remittances in a given country
      subtitle: Remittances include money sent by migrants to their home countries and the salaries of employees employed by foreign companies. Shown is the average transaction cost of receiving US$200, given as a percentage of the total.
      map:
        colorScale:
          baseColorScheme: Oranges
          binningStrategy: manual
          customNumericValues: [0, 2, 4, 6, 8, 10, 12, 14, 16]
    metadata:
      description_key:
        - "{definitions.definition_remittances}"
        - "{definitions.definition_remittances_cost_of_receiving}"
