chart_config_id: 01a061a0-e423-79ce-840c-50bcb9c31c26
topic_tags:
  - "Migration"
dimensions: []
views:
  - dimensions: {}
    indicators:
      y:
        - catalogPath: "us_foreign_born_population/annual_change_by_decade#annual_change"
    config:
      title: "Average annual change in the foreign-born population of the United States"
      subtitle: "Average change per year in the number of people living in the United States who were not US citizens at birth. The value for the 2020s covers 2021 to 2024."
      originUrl: "/migration"
      tab: "chart"
      chartTypes:
        - "StackedBar"
      addCountryMode: "disabled"
      hideAnnotationFieldsInTitle:
        entity: true
      selectedEntityNames:
        - "United States"
