name: Project automations
on:
    issues:
        types:
            - opened
            - reopened
            - labeled
            - unlabeled
    pull_request:
        types:
            - opened
            - reopened
            - review_requested
            - closed

jobs:
    prio:
        name: Sync issue priority to project board
        runs-on: ubuntu-latest
        steps:
            - uses: owid/actions/assign-priority@main
              with:
                  PROJECT_ISSUES_TOKEN: ${{ secrets.PROJECT_ISSUES_TOKEN }}
    status:
        name: Set status based on event
        runs-on: ubuntu-latest
        steps:
            - uses: owid/actions/set-project-status@main
              with:
                  PROJECT_ISSUES_TOKEN: ${{ secrets.PROJECT_ISSUES_TOKEN }}
    needs_triage:
        name: Add "needs triage" label
        runs-on: ubuntu-latest
        if: github.event_name == 'issues' && github.event.action == 'opened'
        steps:
            - name: Label issue
              uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
              with:
                  add-labels: "needs triage"
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
