name: Publish owid-catalog

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Publish owid-catalog to PyPI. Make sure you have bumped the version in catalog/pyproject.toml.'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install UV
      run: curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.POETRY_PYPI_TOKEN_PYPI }}

      run: |
        cd lib/catalog &&
        rm -rf dist &&
        uv build &&
        uvx twine upload dist/*
