name: Publish owid-catalog

on:
  push:
    branches:
      - master
    paths:
      - 'lib/catalog/pyproject.toml'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Publish owid-catalog to PyPI. Make sure you have bumped the version in catalog/pyproject.toml.'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2  # Need previous commit to detect version changes

    - name: Check if version was bumped
      run: |
        # Get the version line from current and previous commit
        CURRENT_VERSION=$(grep '^version = ' lib/catalog/pyproject.toml | head -1)
        PREVIOUS_VERSION=$(git show HEAD~1:lib/catalog/pyproject.toml | grep '^version = ' | head -1)

        echo "Current version: $CURRENT_VERSION"
        echo "Previous version: $PREVIOUS_VERSION"

        if [ "$CURRENT_VERSION" = "$PREVIOUS_VERSION" ]; then
          echo "❌ Version was not bumped in lib/catalog/pyproject.toml"
          echo "Please increment the version before publishing."
          exit 1
        fi

        echo "✅ Version was bumped, proceeding with publish"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install UV
      run: curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.POETRY_PYPI_TOKEN_PYPI }}

      run: |
        cd lib/catalog &&
        rm -rf dist &&
        uv build &&
        uvx twine upload dist/*
