title:
  title: Deaths from air pollution
  title_variant: ""

default_selection:
  - World
  - China
  - India
  - United States
  - South Africa
  - Brazil
  - Indonesia

default_dimensions:
  pollution_type: all
  metric: number

definitions:
  common_views:
    - config:
        originUrl: ourworldindata.org/air-pollution
        hasMapTab: true
        tab: map
        chartTypes:
          - LineChart
          - DiscreteBar
          - SlopeChart
        yAxis:
          min: 0
      metadata:
        description_key:
          - Air pollution is one of the leading risk factors for early death worldwide.
          - Air pollution — particularly very small particles called particulate matter — can infiltrate the lungs, airways and respitatory system, increasing the risk of several of the most common health conditions, including heart disease, stroke, lower respiratory infections, lung cancer, diabetes, and chronic obstructive pulmonary disease (COPD).
          - Indoor, or household, pollution is usually generated from burning wood, other biomass, or charcoal for cooking and heating. This is common in lower-income countries where people do not have alternative, cleaner fuels.
          - Outdoor air pollution is often generated from burning fossil fuels for electricity production, emissions from industry, or tailpipe emissions from vehicles.
          - These estimates of premature deaths come from the Institute for Health Metrics and Evaluation's Global Burden of Disease study.
          - Premature deaths are modelled based on estimates of peoples' exposure to air pollution, and epidemiological models of how this increases the risk of various diseases.
    - dimensions:
        metric: number
      config:
        map:
          colorScale:
            baseColorScheme: OrRd
    - dimensions:
        metric: rate
      config:
        map:
          colorScale:
            baseColorScheme: Purples
    - dimensions:
        metric: share
      config:
        map:
          colorScale:
            baseColorScheme: Oranges

dimensions:
  - slug: pollution_type
    name: Pollution type
    choices:
      - slug: all
        name: Total
        description: Includes both indoor and outdoor air pollution.
      - slug: outdoor
        name: Outdoor
      - slug: indoor
        name: Indoor

  - slug: metric
    name: Metric
    choices:
      - slug: number
        name: Number of deaths
        description: Total number of premature deaths attributed to air pollution.
      - slug: rate
        name: Death rate
        description: Number of premature deaths per 100,000 people.
      - slug: share
        name: Share of deaths
        description: Share of total deaths which are attributed to air pollution.

views:
  # All air pollution
  - dimensions:
      pollution_type: all
      metric: number
    indicators:
      y:
        - catalogPath: grapher/ihme_gbd/2026-02-07/gbd_risk_deaths/gbd_risk_deaths#value__metric_number__measure_deaths__rei_air_pollution__age_all_ages__cause_all_causes
    config:
      title: Deaths from air pollution
      subtitle: Estimated premature deaths attributed to air pollution. This means people died earlier than they would have in the absence of air pollution. This includes indoor household pollution, outdoor particulate matter and ozone pollution.

  - dimensions:
      pollution_type: all
      metric: rate
    indicators:
      y:
        - catalogPath: grapher/ihme_gbd/2026-02-07/gbd_risk_deaths/gbd_risk_deaths#value__metric_rate__measure_deaths__rei_air_pollution__age_age_standardized__cause_all_causes
    config:
      title: Death rate from air pollution
      subtitle: Estimated premature deaths attributed to air pollution per 100,000 people. This means people died earlier than they would have in the absence of pollution.
      note: To allow for comparisons between countries and over time, this metric is age-standardized.

  - dimensions:
      pollution_type: all
      metric: share
    indicators:
      y:
        - catalogPath: grapher/ihme_gbd/2026-02-07/gbd_risk_deaths/gbd_risk_deaths#value__metric_percent__measure_deaths__rei_air_pollution__age_age_standardized__cause_all_causes
    config:
      title: Share of deaths attributed to air pollution
      subtitle: Share of deaths, from any cause, which are attributed to air pollution – from outdoor and indoor sources – as a risk factor.

  # Outdoor air pollution
  - dimensions:
      pollution_type: outdoor
      metric: number
    indicators:
      y:
        - catalogPath: grapher/ihme_gbd/2026-02-07/gbd_risk_deaths/gbd_risk_deaths#value__metric_number__measure_deaths__rei_ambient_particulate_matter_pollution__age_all_ages__cause_all_causes
    config:
      title: Deaths from outdoor air pollution
      subtitle: Estimated premature deaths attributed to outdoor air pollution. This means people died earlier than they would have in the absence of outdoor particulate matter pollution.

  - dimensions:
      pollution_type: outdoor
      metric: rate
    indicators:
      y:
        - catalogPath: grapher/ihme_gbd/2026-02-07/gbd_risk_deaths/gbd_risk_deaths#value__metric_rate__measure_deaths__rei_ambient_particulate_matter_pollution__age_age_standardized__cause_all_causes
    config:
      title: Outdoor air pollution death rate
      subtitle: Estimated premature deaths attributed to outdoor air pollution per 100,000 people. This means people died earlier than they would have in the absence of pollution.
      note: To allow for comparisons between countries and over time, this metric is age-standardized.

  - dimensions:
      pollution_type: outdoor
      metric: share
    indicators:
      y:
        - catalogPath: grapher/ihme_gbd/2026-02-07/gbd_risk_deaths/gbd_risk_deaths#value__metric_percent__measure_deaths__rei_ambient_particulate_matter_pollution__age_all_ages__cause_all_causes
    config:
      title: Share of deaths attributed to outdoor air pollution
      subtitle: Share of deaths, from any cause, where ambient particulate matter air pollution is a risk factor.

  # Indoor air pollution
  - dimensions:
      pollution_type: indoor
      metric: number
    indicators:
      y:
        - catalogPath: grapher/ihme_gbd/2026-02-07/gbd_risk_deaths/gbd_risk_deaths#value__metric_number__measure_deaths__rei_household_air_pollution_from_solid_fuels__age_all_ages__cause_all_causes
    config:
      title: Deaths from indoor air pollution
      subtitle: Estimated premature deaths attributed to indoor air pollution. This means people died earlier than they would have in the absence of indoor air pollution from solid fuels used for cooking and heating.

  - dimensions:
      pollution_type: indoor
      metric: rate
    indicators:
      y:
        - catalogPath: grapher/ihme_gbd/2026-02-07/gbd_risk_deaths/gbd_risk_deaths#value__metric_rate__measure_deaths__rei_household_air_pollution_from_solid_fuels__age_age_standardized__cause_all_causes
    config:
      title: Death rate from indoor air pollution
      subtitle: Estimated premature deaths attributed to indoor air pollution per 100,000 people. This means people died earlier than they would have in the absence of pollution.
      note: To allow for comparisons between countries and over time, this metric is age-standardized.

  - dimensions:
      pollution_type: indoor
      metric: share
    indicators:
      y:
        - catalogPath: grapher/ihme_gbd/2026-02-07/gbd_risk_deaths/gbd_risk_deaths#value__metric_percent__measure_deaths__rei_household_air_pollution_from_solid_fuels__age_age_standardized__cause_all_causes
    config:
      title: Share of deaths from indoor air pollution
      subtitle: Share of deaths, from any cause, which are attributed to indoor air pollution – from burning solid fuels – as a risk factor.
